# Copied from PandoraLauncher (https://github.com/Moulberry/PandoraLauncher),
# crates/nbt. MIT, Copyright (c) 2025 Moulberry -- see THIRD_PARTY_NOTICES.md
# and licenses/PandoraLauncher-LICENSE.txt. The only difference from upstream is
# this manifest: dependency versions are spelled out here rather than inherited
# from Pandora's workspace.
[package]
name = "nbt"
description = "PandoraLauncher's NBT reader and writer, adopted by PalantirMC"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
authors = ["Moulberry"]
repository = "https://github.com/Moulberry/PandoraLauncher"

[dependencies]
slab = "0.4.11"
anyhow = "1.0.100"
byteorder = "1.5.0"
bytes = "1.10.1"
paste = "1.0.15"
num = "0.4.3"
cesu8 = "1.1.0"
