//! The reference's full token vocabulary, generated -- not written by hand.
//!
//! `python tools/gen_tokens.py` reads the vendored sheets at the commit
//! `UPSTREAM.md` pins (8966b5e2e7951e83651fbebbf2fb6d7608a94a33) and emits every `--token` the reference
//! declares, per mode, after the reference's own cascade and with `var()`
//! chains followed to the end. 189 light, 189 dark, 189 oled, 189 retro
//!
//! This file is the shell's *copy* of the vocabulary. Whether that copy is
//! still the sheets is not taken on trust: `the_generated_vocabulary_is_the_sheets`
//! re-reads the sheets itself and fails here, naming the file and line the
//! reference states the moved token on, when the two disagree. So the rule is:
//! never edit this file by hand -- change the sheet or the generator, run the
//! generator, commit what it writes.
//!
//! Compiled into the test build only (`#[cfg(test)]` in `main.rs`): the
//! palette paints from `theme.rs`, and this copy is what the vocabulary gate
//! checks the sheets against. When a page starts consuming a token at
//! runtime, the token moves into `theme.rs` and this row stays the receipt.
//!
//! `Kind::Text` holds everything the reference declares that has no drawn
//! answer here (its `hsla()` shadows, its font stacks): the shell holds the
//! token, and a claim that needs the value fails loudly instead of quietly
//! matching nothing.

//! Generated from assets/styles/variables.scss and assets/styles/defaults.scss.

/// What kind of value a resolved token carries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    /// A colour, encoded `#rrggbb` or `#rrggbbaa` when the reference writes an
    /// alpha into it.
    Color,
    /// A length, in px, at the reference's 16px root.
    Length,
    /// A unitless number.
    Number,
    /// A gradient's stops, encoded `#rrggbbaa@position`, position in percent,
    /// comma-separated, in order.
    Gradient,
    /// Anything else the reference declares -- shadows, font stacks, blend
    /// modes -- kept as the reference's own text.
    Text,
}

/// One token of the vocabulary, with the file and line it is declared on.
#[derive(Debug, Clone, Copy)]
pub struct Row {
    pub token: &'static str,
    pub file: &'static str,
    pub line: u32,
    pub kind: Kind,
    pub value: &'static str,
}

pub const LIGHT: &[Row] = &[
    Row { token: "--brand-gradient-bg", file: "variables.scss", line: 142, kind: Kind::Gradient, value: "#44b68a2d@0,#3afa7020@100" },
    Row { token: "--brand-gradient-border", file: "variables.scss", line: 153, kind: Kind::Color, value: "#20402026" },
    Row { token: "--brand-gradient-button", file: "variables.scss", line: 152, kind: Kind::Color, value: "#ffffff80" },
    Row { token: "--brand-gradient-fade-out-color", file: "variables.scss", line: 154, kind: Kind::Text, value: "linear-gradient(to bottom, rgba(213, 235, 224, 0), #d0ece0 70%)" },
    Row { token: "--brand-gradient-strong-bg", file: "variables.scss", line: 147, kind: Kind::Gradient, value: "#44b68a2d@0,#24e15b1f@100" },
    Row { token: "--color-accent-contrast", file: "variables.scss", line: 108, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--color-ad", file: "variables.scss", line: 211, kind: Kind::Color, value: "#7d4ba233" },
    Row { token: "--color-ad-contrast", file: "variables.scss", line: 213, kind: Kind::Color, value: "#000000" },
    Row { token: "--color-ad-highlight", file: "variables.scss", line: 68, kind: Kind::Color, value: "#8e32f3" },
    Row { token: "--color-ad-raised", file: "variables.scss", line: 212, kind: Kind::Color, value: "#be8cf380" },
    Row { token: "--color-base", file: "variables.scss", line: 89, kind: Kind::Color, value: "#2c2e31" },
    Row { token: "--color-bg", file: "variables.scss", line: 2, kind: Kind::Color, value: "#ebebeb" },
    Row { token: "--color-blue", file: "variables.scss", line: 55, kind: Kind::Color, value: "#1f68c0" },
    Row { token: "--color-blue-100", file: "variables.scss", line: 50, kind: Kind::Color, value: "#e4ecfa" },
    Row { token: "--color-blue-200", file: "variables.scss", line: 51, kind: Kind::Color, value: "#c3d9f4" },
    Row { token: "--color-blue-300", file: "variables.scss", line: 52, kind: Kind::Color, value: "#8ebaeb" },
    Row { token: "--color-blue-400", file: "variables.scss", line: 53, kind: Kind::Color, value: "#5196df" },
    Row { token: "--color-blue-50", file: "variables.scss", line: 49, kind: Kind::Color, value: "#f2f7fd" },
    Row { token: "--color-blue-500", file: "variables.scss", line: 54, kind: Kind::Color, value: "#2b79cc" },
    Row { token: "--color-blue-600", file: "variables.scss", line: 55, kind: Kind::Color, value: "#1f68c0" },
    Row { token: "--color-blue-700", file: "variables.scss", line: 56, kind: Kind::Color, value: "#184b8c" },
    Row { token: "--color-blue-800", file: "variables.scss", line: 57, kind: Kind::Color, value: "#184174" },
    Row { token: "--color-blue-900", file: "variables.scss", line: 58, kind: Kind::Color, value: "#193861" },
    Row { token: "--color-blue-950", file: "variables.scss", line: 59, kind: Kind::Color, value: "#112340" },
    Row { token: "--color-blue-bg", file: "variables.scss", line: 120, kind: Kind::Color, value: "#1f68c01a" },
    Row { token: "--color-blue-highlight", file: "variables.scss", line: 113, kind: Kind::Color, value: "#1f68c040" },
    Row { token: "--color-brand", file: "variables.scss", line: 42, kind: Kind::Color, value: "#00af5c" },
    Row { token: "--color-brand-highlight", file: "variables.scss", line: 112, kind: Kind::Color, value: "#00af5c40" },
    Row { token: "--color-brand-shadow", file: "variables.scss", line: 125, kind: Kind::Color, value: "#00af5cb3" },
    Row { token: "--color-button-bg", file: "variables.scss", line: 7, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--color-button-bg-selected", file: "variables.scss", line: 42, kind: Kind::Color, value: "#00af5c" },
    Row { token: "--color-button-border", file: "variables.scss", line: 99, kind: Kind::Color, value: "#a1a1a159" },
    Row { token: "--color-button-text-selected", file: "variables.scss", line: 108, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--color-contrast", file: "variables.scss", line: 88, kind: Kind::Color, value: "#1a202c" },
    Row { token: "--color-divider", file: "variables.scss", line: 8, kind: Kind::Color, value: "#dddddd" },
    Row { token: "--color-divider-dark", file: "variables.scss", line: 8, kind: Kind::Color, value: "#dddddd" },
    Row { token: "--color-focus-ring", file: "variables.scss", line: 222, kind: Kind::Color, value: "#ea80ff" },
    Row { token: "--color-gradient-button-bg", file: "variables.scss", line: 159, kind: Kind::Gradient, value: "#f8f9fa@0,#dce0e6@100" },
    Row { token: "--color-gray", file: "variables.scss", line: 81, kind: Kind::Color, value: "#595b61" },
    Row { token: "--color-gray-100", file: "variables.scss", line: 76, kind: Kind::Color, value: "#e5e5e8" },
    Row { token: "--color-gray-200", file: "variables.scss", line: 77, kind: Kind::Color, value: "#cecfd3" },
    Row { token: "--color-gray-300", file: "variables.scss", line: 78, kind: Kind::Color, value: "#adb0b3" },
    Row { token: "--color-gray-400", file: "variables.scss", line: 79, kind: Kind::Color, value: "#83868d" },
    Row { token: "--color-gray-50", file: "variables.scss", line: 75, kind: Kind::Color, value: "#f5f5f6" },
    Row { token: "--color-gray-500", file: "variables.scss", line: 80, kind: Kind::Color, value: "#686a72" },
    Row { token: "--color-gray-600", file: "variables.scss", line: 81, kind: Kind::Color, value: "#595b61" },
    Row { token: "--color-gray-700", file: "variables.scss", line: 82, kind: Kind::Color, value: "#4c4e52" },
    Row { token: "--color-gray-800", file: "variables.scss", line: 83, kind: Kind::Color, value: "#434447" },
    Row { token: "--color-gray-900", file: "variables.scss", line: 84, kind: Kind::Color, value: "#3b3b3e" },
    Row { token: "--color-gray-950", file: "variables.scss", line: 85, kind: Kind::Color, value: "#252627" },
    Row { token: "--color-gray-highlight", file: "variables.scss", line: 115, kind: Kind::Color, value: "#595b6140" },
    Row { token: "--color-green", file: "variables.scss", line: 42, kind: Kind::Color, value: "#00af5c" },
    Row { token: "--color-green-100", file: "variables.scss", line: 37, kind: Kind::Color, value: "#d7ffeb" },
    Row { token: "--color-green-200", file: "variables.scss", line: 38, kind: Kind::Color, value: "#b2ffd9" },
    Row { token: "--color-green-300", file: "variables.scss", line: 39, kind: Kind::Color, value: "#76ffbc" },
    Row { token: "--color-green-400", file: "variables.scss", line: 40, kind: Kind::Color, value: "#33f598" },
    Row { token: "--color-green-50", file: "variables.scss", line: 36, kind: Kind::Color, value: "#eefff6" },
    Row { token: "--color-green-500", file: "variables.scss", line: 41, kind: Kind::Color, value: "#09de78" },
    Row { token: "--color-green-600", file: "variables.scss", line: 42, kind: Kind::Color, value: "#00af5c" },
    Row { token: "--color-green-700", file: "variables.scss", line: 43, kind: Kind::Color, value: "#04914f" },
    Row { token: "--color-green-800", file: "variables.scss", line: 44, kind: Kind::Color, value: "#0a7141" },
    Row { token: "--color-green-900", file: "variables.scss", line: 45, kind: Kind::Color, value: "#0a5d38" },
    Row { token: "--color-green-950", file: "variables.scss", line: 46, kind: Kind::Color, value: "#00341d" },
    Row { token: "--color-green-bg", file: "variables.scss", line: 119, kind: Kind::Color, value: "#00af5c1a" },
    Row { token: "--color-green-highlight", file: "variables.scss", line: 112, kind: Kind::Color, value: "#00af5c40" },
    Row { token: "--color-link", file: "variables.scss", line: 55, kind: Kind::Color, value: "#1f68c0" },
    Row { token: "--color-link-active", file: "variables.scss", line: 55, kind: Kind::Color, value: "#1f68c0" },
    Row { token: "--color-link-hover", file: "variables.scss", line: 55, kind: Kind::Color, value: "#1f68c0" },
    Row { token: "--color-orange", file: "variables.scss", line: 28, kind: Kind::Color, value: "#e08325" },
    Row { token: "--color-orange-100", file: "variables.scss", line: 24, kind: Kind::Color, value: "#f9eacc" },
    Row { token: "--color-orange-200", file: "variables.scss", line: 25, kind: Kind::Color, value: "#f2d495" },
    Row { token: "--color-orange-300", file: "variables.scss", line: 26, kind: Kind::Color, value: "#ecb85d" },
    Row { token: "--color-orange-400", file: "variables.scss", line: 27, kind: Kind::Color, value: "#e7a038" },
    Row { token: "--color-orange-50", file: "variables.scss", line: 23, kind: Kind::Color, value: "#fdf8ed" },
    Row { token: "--color-orange-500", file: "variables.scss", line: 28, kind: Kind::Color, value: "#e08325" },
    Row { token: "--color-orange-600", file: "variables.scss", line: 29, kind: Kind::Color, value: "#c66019" },
    Row { token: "--color-orange-700", file: "variables.scss", line: 30, kind: Kind::Color, value: "#a44419" },
    Row { token: "--color-orange-800", file: "variables.scss", line: 31, kind: Kind::Color, value: "#86351a" },
    Row { token: "--color-orange-900", file: "variables.scss", line: 32, kind: Kind::Color, value: "#6e2d19" },
    Row { token: "--color-orange-950", file: "variables.scss", line: 33, kind: Kind::Color, value: "#3f1509" },
    Row { token: "--color-orange-bg", file: "variables.scss", line: 118, kind: Kind::Color, value: "#e083251a" },
    Row { token: "--color-orange-highlight", file: "variables.scss", line: 111, kind: Kind::Color, value: "#e0832540" },
    Row { token: "--color-platform-bta-babric", file: "variables.scss", line: 184, kind: Kind::Color, value: "#5ba938" },
    Row { token: "--color-platform-bukkit", file: "variables.scss", line: 174, kind: Kind::Color, value: "#e78362" },
    Row { token: "--color-platform-bungeecord", file: "variables.scss", line: 175, kind: Kind::Color, value: "#c69e39" },
    Row { token: "--color-platform-fabric", file: "variables.scss", line: 169, kind: Kind::Color, value: "#8a7b71" },
    Row { token: "--color-platform-folia", file: "variables.scss", line: 176, kind: Kind::Color, value: "#6aa54f" },
    Row { token: "--color-platform-forge", file: "variables.scss", line: 171, kind: Kind::Color, value: "#5b6197" },
    Row { token: "--color-platform-liteloader", file: "variables.scss", line: 173, kind: Kind::Color, value: "#4c90de" },
    Row { token: "--color-platform-neoforge", file: "variables.scss", line: 172, kind: Kind::Color, value: "#dc895c" },
    Row { token: "--color-platform-nilloader", file: "variables.scss", line: 185, kind: Kind::Color, value: "#dd5088" },
    Row { token: "--color-platform-ornithe", file: "variables.scss", line: 183, kind: Kind::Color, value: "#6097ca" },
    Row { token: "--color-platform-paper", file: "variables.scss", line: 177, kind: Kind::Color, value: "#e67e7e" },
    Row { token: "--color-platform-purpur", file: "variables.scss", line: 178, kind: Kind::Color, value: "#7763a3" },
    Row { token: "--color-platform-quilt", file: "variables.scss", line: 170, kind: Kind::Color, value: "#8b61b4" },
    Row { token: "--color-platform-spigot", file: "variables.scss", line: 179, kind: Kind::Color, value: "#cd7a21" },
    Row { token: "--color-platform-sponge", file: "variables.scss", line: 182, kind: Kind::Color, value: "#c49528" },
    Row { token: "--color-platform-velocity", file: "variables.scss", line: 180, kind: Kind::Color, value: "#4b98b0" },
    Row { token: "--color-platform-waterfall", file: "variables.scss", line: 181, kind: Kind::Color, value: "#5f83cb" },
    Row { token: "--color-purple", file: "variables.scss", line: 68, kind: Kind::Color, value: "#8e32f3" },
    Row { token: "--color-purple-100", file: "variables.scss", line: 63, kind: Kind::Color, value: "#f2e7ff" },
    Row { token: "--color-purple-200", file: "variables.scss", line: 64, kind: Kind::Color, value: "#e7d3ff" },
    Row { token: "--color-purple-300", file: "variables.scss", line: 65, kind: Kind::Color, value: "#d4b1ff" },
    Row { token: "--color-purple-400", file: "variables.scss", line: 66, kind: Kind::Color, value: "#ba7eff" },
    Row { token: "--color-purple-50", file: "variables.scss", line: 62, kind: Kind::Color, value: "#faf5ff" },
    Row { token: "--color-purple-500", file: "variables.scss", line: 67, kind: Kind::Color, value: "#9f4dff" },
    Row { token: "--color-purple-600", file: "variables.scss", line: 68, kind: Kind::Color, value: "#8e32f3" },
    Row { token: "--color-purple-700", file: "variables.scss", line: 69, kind: Kind::Color, value: "#761ad6" },
    Row { token: "--color-purple-800", file: "variables.scss", line: 70, kind: Kind::Color, value: "#651bae" },
    Row { token: "--color-purple-900", file: "variables.scss", line: 71, kind: Kind::Color, value: "#53178c" },
    Row { token: "--color-purple-950", file: "variables.scss", line: 72, kind: Kind::Color, value: "#370368" },
    Row { token: "--color-purple-bg", file: "variables.scss", line: 121, kind: Kind::Color, value: "#8e32f31a" },
    Row { token: "--color-purple-highlight", file: "variables.scss", line: 114, kind: Kind::Color, value: "#8e32f340" },
    Row { token: "--color-raised-bg", file: "variables.scss", line: 6, kind: Kind::Color, value: "#f8f8f8" },
    Row { token: "--color-red", file: "variables.scss", line: 16, kind: Kind::Color, value: "#cb2245" },
    Row { token: "--color-red-100", file: "variables.scss", line: 11, kind: Kind::Color, value: "#fee5e7" },
    Row { token: "--color-red-200", file: "variables.scss", line: 12, kind: Kind::Color, value: "#fccfd3" },
    Row { token: "--color-red-300", file: "variables.scss", line: 13, kind: Kind::Color, value: "#faa7b1" },
    Row { token: "--color-red-400", file: "variables.scss", line: 14, kind: Kind::Color, value: "#f67687" },
    Row { token: "--color-red-50", file: "variables.scss", line: 10, kind: Kind::Color, value: "#fef2f2" },
    Row { token: "--color-red-500", file: "variables.scss", line: 15, kind: Kind::Color, value: "#ed4661" },
    Row { token: "--color-red-600", file: "variables.scss", line: 16, kind: Kind::Color, value: "#cb2245" },
    Row { token: "--color-red-700", file: "variables.scss", line: 17, kind: Kind::Color, value: "#b7193d" },
    Row { token: "--color-red-800", file: "variables.scss", line: 18, kind: Kind::Color, value: "#9a1739" },
    Row { token: "--color-red-900", file: "variables.scss", line: 19, kind: Kind::Color, value: "#841738" },
    Row { token: "--color-red-950", file: "variables.scss", line: 20, kind: Kind::Color, value: "#490819" },
    Row { token: "--color-red-bg", file: "variables.scss", line: 117, kind: Kind::Color, value: "#cb22451a" },
    Row { token: "--color-red-highlight", file: "variables.scss", line: 110, kind: Kind::Color, value: "#cb224540" },
    Row { token: "--color-scrollbar", file: "variables.scss", line: 100, kind: Kind::Color, value: "#96a2b0" },
    Row { token: "--color-secondary", file: "variables.scss", line: 90, kind: Kind::Color, value: "#484d54" },
    Row { token: "--color-super-raised-bg", file: "variables.scss", line: 7, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--color-text-default", file: "variables.scss", line: 89, kind: Kind::Color, value: "#2c2e31" },
    Row { token: "--color-text-primary", file: "variables.scss", line: 88, kind: Kind::Color, value: "#1a202c" },
    Row { token: "--color-text-tertiary", file: "variables.scss", line: 90, kind: Kind::Color, value: "#484d54" },
    Row { token: "--color-tooltip-bg", file: "variables.scss", line: 6, kind: Kind::Color, value: "#f8f8f8" },
    Row { token: "--color-tooltip-text", file: "variables.scss", line: 88, kind: Kind::Color, value: "#1a202c" },
    Row { token: "--dark-color-base", file: "variables.scss", line: 192, kind: Kind::Color, value: "#b0bac5" },
    Row { token: "--dark-color-contrast", file: "variables.scss", line: 193, kind: Kind::Color, value: "#ecf9fb" },
    Row { token: "--font-size-2xl", file: "defaults.scss", line: 30, kind: Kind::Length, value: "32" },
    Row { token: "--font-size-3xl", file: "defaults.scss", line: 31, kind: Kind::Length, value: "48" },
    Row { token: "--font-size-lg", file: "defaults.scss", line: 28, kind: Kind::Length, value: "20" },
    Row { token: "--font-size-md", file: "defaults.scss", line: 27, kind: Kind::Length, value: "18" },
    Row { token: "--font-size-nm", file: "defaults.scss", line: 26, kind: Kind::Length, value: "16" },
    Row { token: "--font-size-sm", file: "defaults.scss", line: 25, kind: Kind::Length, value: "14" },
    Row { token: "--font-size-xl", file: "defaults.scss", line: 29, kind: Kind::Length, value: "24" },
    Row { token: "--font-size-xs", file: "defaults.scss", line: 24, kind: Kind::Length, value: "12" },
    Row { token: "--font-size-xxs", file: "defaults.scss", line: 23, kind: Kind::Length, value: "10" },
    Row { token: "--font-standard", file: "defaults.scss", line: 12, kind: Kind::Text, value: "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Oxygen, Ubuntu, Roboto, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif" },
    Row { token: "--font-weight-bold", file: "defaults.scss", line: 36, kind: Kind::Number, value: "700" },
    Row { token: "--font-weight-extrabold", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--font-weight-heading", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--font-weight-medium", file: "defaults.scss", line: 35, kind: Kind::Number, value: "500" },
    Row { token: "--font-weight-regular", file: "defaults.scss", line: 34, kind: Kind::Number, value: "400" },
    Row { token: "--font-weight-text", file: "defaults.scss", line: 35, kind: Kind::Number, value: "500" },
    Row { token: "--font-weight-title", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--gap-lg", file: "variables.scss", line: 198, kind: Kind::Length, value: "16" },
    Row { token: "--gap-md", file: "variables.scss", line: 197, kind: Kind::Length, value: "12" },
    Row { token: "--gap-sm", file: "variables.scss", line: 196, kind: Kind::Length, value: "8" },
    Row { token: "--gap-xl", file: "variables.scss", line: 199, kind: Kind::Length, value: "24" },
    Row { token: "--gap-xs", file: "variables.scss", line: 195, kind: Kind::Length, value: "4" },
    Row { token: "--hover-brightness", file: "variables.scss", line: 187, kind: Kind::Number, value: "0.9" },
    Row { token: "--loading-bar-gradient", file: "variables.scss", line: 161, kind: Kind::Text, value: "linear-gradient(to right, var(--color-brand) 0%, #00af5c 100%)" },
    Row { token: "--mono-font", file: "defaults.scss", line: 15, kind: Kind::Text, value: "ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace" },
    Row { token: "--radius-lg", file: "variables.scss", line: 204, kind: Kind::Length, value: "16" },
    Row { token: "--radius-max", file: "variables.scss", line: 206, kind: Kind::Length, value: "999999999" },
    Row { token: "--radius-md", file: "variables.scss", line: 203, kind: Kind::Length, value: "12" },
    Row { token: "--radius-sm", file: "variables.scss", line: 202, kind: Kind::Length, value: "8" },
    Row { token: "--radius-xl", file: "variables.scss", line: 205, kind: Kind::Length, value: "20" },
    Row { token: "--radius-xs", file: "variables.scss", line: 201, kind: Kind::Length, value: "4" },
    Row { token: "--shadow-button", file: "variables.scss", line: 220, kind: Kind::Text, value: "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.15)" },
    Row { token: "--shadow-card", file: "variables.scss", line: 140, kind: Kind::Text, value: "rgba(50, 50, 100, 0.1) 0px 2px 4px 0px" },
    Row { token: "--shadow-floating", file: "variables.scss", line: 136, kind: Kind::Text, value: "hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0.1) 0px 4px 6px -1px, hsla(0, 0%, 0%, 0.1) 0px 2px 4px -1px" },
    Row { token: "--shadow-inset", file: "variables.scss", line: 128, kind: Kind::Text, value: "inset 0px -2px 2px hsla(221, 39%, 91%, 0.05)" },
    Row { token: "--shadow-inset-lg", file: "variables.scss", line: 127, kind: Kind::Text, value: "inset 0px -2px 2px hsla(221, 39%, 91%, 0.1)" },
    Row { token: "--shadow-inset-sm", file: "variables.scss", line: 129, kind: Kind::Text, value: "inset 0px -1px 2px hsla(221, 39%, 91%, 0.15)" },
    Row { token: "--shadow-raised", file: "variables.scss", line: 132, kind: Kind::Text, value: "0.3px 0.5px 0.6px hsl(var(--shadow-color) / 0.15), 1px 2px 2.2px -1.7px hsl(var(--shadow-color) / 0.12), 4.4px 8.8px 9.7px -3.4px hsl(var(--shadow-color) / 0.09)" },
    Row { token: "--shadow-raised-lg", file: "variables.scss", line: 131, kind: Kind::Text, value: "0px 2px 4px hsla(221, 39%, 11%, 0.2)" },
    Row { token: "--splash-cube-blend", file: "variables.scss", line: 167, kind: Kind::Text, value: "multiply" },
    Row { token: "--splash-cube-opacity", file: "variables.scss", line: 166, kind: Kind::Number, value: "0.4" },
    Row { token: "--splash-overlay", file: "variables.scss", line: 165, kind: Kind::Color, value: "#b5ffd550" },
    Row { token: "--splash-tint-bottom", file: "variables.scss", line: 164, kind: Kind::Color, value: "#b7e2ff90" },
    Row { token: "--splash-tint-top", file: "variables.scss", line: 163, kind: Kind::Color, value: "#b9ffcf77" },
    Row { token: "--surface-1", file: "variables.scss", line: 2, kind: Kind::Color, value: "#ebebeb" },
    Row { token: "--surface-1-5", file: "variables.scss", line: 3, kind: Kind::Color, value: "#ededed" },
    Row { token: "--surface-2", file: "variables.scss", line: 4, kind: Kind::Color, value: "#f5f5f5" },
    Row { token: "--surface-2-5", file: "variables.scss", line: 5, kind: Kind::Color, value: "#eef1f5" },
    Row { token: "--surface-3", file: "variables.scss", line: 6, kind: Kind::Color, value: "#f8f8f8" },
    Row { token: "--surface-4", file: "variables.scss", line: 7, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--surface-5", file: "variables.scss", line: 8, kind: Kind::Color, value: "#dddddd" },
];

pub const DARK: &[Row] = &[
    Row { token: "--brand-gradient-bg", file: "variables.scss", line: 370, kind: Kind::Gradient, value: "#0e231333@0,#3789491a@100" },
    Row { token: "--brand-gradient-border", file: "variables.scss", line: 373, kind: Kind::Color, value: "#9bffa014" },
    Row { token: "--brand-gradient-button", file: "variables.scss", line: 372, kind: Kind::Color, value: "#ffffff14" },
    Row { token: "--brand-gradient-fade-out-color", file: "variables.scss", line: 374, kind: Kind::Text, value: "linear-gradient(to bottom, rgba(24, 30, 31, 0), #171d1e 80%)" },
    Row { token: "--brand-gradient-strong-bg", file: "variables.scss", line: 371, kind: Kind::Gradient, value: "#09110d@10,#131f17@100" },
    Row { token: "--color-accent-contrast", file: "variables.scss", line: 339, kind: Kind::Color, value: "#000000" },
    Row { token: "--color-ad", file: "variables.scss", line: 211, kind: Kind::Color, value: "#7d4ba233" },
    Row { token: "--color-ad-contrast", file: "variables.scss", line: 213, kind: Kind::Color, value: "#000000" },
    Row { token: "--color-ad-highlight", file: "variables.scss", line: 297, kind: Kind::Color, value: "#c78aff" },
    Row { token: "--color-ad-raised", file: "variables.scss", line: 212, kind: Kind::Color, value: "#be8cf380" },
    Row { token: "--color-base", file: "variables.scss", line: 320, kind: Kind::Color, value: "#b0bac5" },
    Row { token: "--color-bg", file: "variables.scss", line: 233, kind: Kind::Color, value: "#16181c" },
    Row { token: "--color-blue", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-blue-100", file: "variables.scss", line: 281, kind: Kind::Color, value: "#daeaff" },
    Row { token: "--color-blue-200", file: "variables.scss", line: 282, kind: Kind::Color, value: "#bddaff" },
    Row { token: "--color-blue-300", file: "variables.scss", line: 283, kind: Kind::Color, value: "#90c4ff" },
    Row { token: "--color-blue-400", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-blue-50", file: "variables.scss", line: 280, kind: Kind::Color, value: "#eef6ff" },
    Row { token: "--color-blue-500", file: "variables.scss", line: 285, kind: Kind::Color, value: "#357ffc" },
    Row { token: "--color-blue-600", file: "variables.scss", line: 286, kind: Kind::Color, value: "#1f5ff1" },
    Row { token: "--color-blue-700", file: "variables.scss", line: 287, kind: Kind::Color, value: "#1749de" },
    Row { token: "--color-blue-800", file: "variables.scss", line: 288, kind: Kind::Color, value: "#193cb4" },
    Row { token: "--color-blue-900", file: "variables.scss", line: 289, kind: Kind::Color, value: "#1a378e" },
    Row { token: "--color-blue-950", file: "variables.scss", line: 290, kind: Kind::Color, value: "#152356" },
    Row { token: "--color-blue-bg", file: "variables.scss", line: 351, kind: Kind::Color, value: "#4f9cff33" },
    Row { token: "--color-blue-highlight", file: "variables.scss", line: 344, kind: Kind::Color, value: "#4f9cff40" },
    Row { token: "--color-brand", file: "variables.scss", line: 272, kind: Kind::Color, value: "#1bd96a" },
    Row { token: "--color-brand-highlight", file: "variables.scss", line: 355, kind: Kind::Color, value: "#1bd96a40" },
    Row { token: "--color-brand-shadow", file: "variables.scss", line: 356, kind: Kind::Color, value: "#1bd96ab3" },
    Row { token: "--color-button-bg", file: "variables.scss", line: 238, kind: Kind::Color, value: "#34363c" },
    Row { token: "--color-button-bg-selected", file: "variables.scss", line: 355, kind: Kind::Color, value: "#1bd96a40" },
    Row { token: "--color-button-border", file: "variables.scss", line: 330, kind: Kind::Color, value: "#c1bed11f" },
    Row { token: "--color-button-text-selected", file: "variables.scss", line: 272, kind: Kind::Color, value: "#1bd96a" },
    Row { token: "--color-contrast", file: "variables.scss", line: 319, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--color-divider", file: "variables.scss", line: 238, kind: Kind::Color, value: "#34363c" },
    Row { token: "--color-divider-dark", file: "variables.scss", line: 334, kind: Kind::Color, value: "#646c75" },
    Row { token: "--color-focus-ring", file: "variables.scss", line: 222, kind: Kind::Color, value: "#ea80ff" },
    Row { token: "--color-gradient-button-bg", file: "variables.scss", line: 379, kind: Kind::Gradient, value: "#3a3d47@0,#33363d@100" },
    Row { token: "--color-gray", file: "variables.scss", line: 311, kind: Kind::Color, value: "#9fa4b3" },
    Row { token: "--color-gray-100", file: "variables.scss", line: 307, kind: Kind::Color, value: "#edeff2" },
    Row { token: "--color-gray-200", file: "variables.scss", line: 308, kind: Kind::Color, value: "#dfe2e6" },
    Row { token: "--color-gray-300", file: "variables.scss", line: 309, kind: Kind::Color, value: "#cad0d7" },
    Row { token: "--color-gray-400", file: "variables.scss", line: 310, kind: Kind::Color, value: "#b4bac5" },
    Row { token: "--color-gray-50", file: "variables.scss", line: 306, kind: Kind::Color, value: "#f5f7f8" },
    Row { token: "--color-gray-500", file: "variables.scss", line: 311, kind: Kind::Color, value: "#9fa4b3" },
    Row { token: "--color-gray-600", file: "variables.scss", line: 312, kind: Kind::Color, value: "#8a8da1" },
    Row { token: "--color-gray-700", file: "variables.scss", line: 313, kind: Kind::Color, value: "#777b8b" },
    Row { token: "--color-gray-800", file: "variables.scss", line: 314, kind: Kind::Color, value: "#616472" },
    Row { token: "--color-gray-900", file: "variables.scss", line: 315, kind: Kind::Color, value: "#52555d" },
    Row { token: "--color-gray-950", file: "variables.scss", line: 316, kind: Kind::Color, value: "#303136" },
    Row { token: "--color-gray-highlight", file: "variables.scss", line: 346, kind: Kind::Color, value: "#9fa4b340" },
    Row { token: "--color-green", file: "variables.scss", line: 272, kind: Kind::Color, value: "#1bd96a" },
    Row { token: "--color-green-100", file: "variables.scss", line: 268, kind: Kind::Color, value: "#dafee8" },
    Row { token: "--color-green-200", file: "variables.scss", line: 269, kind: Kind::Color, value: "#b8fad2" },
    Row { token: "--color-green-300", file: "variables.scss", line: 270, kind: Kind::Color, value: "#81f4af" },
    Row { token: "--color-green-400", file: "variables.scss", line: 271, kind: Kind::Color, value: "#42e686" },
    Row { token: "--color-green-50", file: "variables.scss", line: 267, kind: Kind::Color, value: "#effef5" },
    Row { token: "--color-green-500", file: "variables.scss", line: 272, kind: Kind::Color, value: "#1bd96a" },
    Row { token: "--color-green-600", file: "variables.scss", line: 273, kind: Kind::Color, value: "#0faa4f" },
    Row { token: "--color-green-700", file: "variables.scss", line: 274, kind: Kind::Color, value: "#0f8642" },
    Row { token: "--color-green-800", file: "variables.scss", line: 275, kind: Kind::Color, value: "#126937" },
    Row { token: "--color-green-900", file: "variables.scss", line: 276, kind: Kind::Color, value: "#11562f" },
    Row { token: "--color-green-950", file: "variables.scss", line: 277, kind: Kind::Color, value: "#033018" },
    Row { token: "--color-green-bg", file: "variables.scss", line: 350, kind: Kind::Color, value: "#1bd96a33" },
    Row { token: "--color-green-highlight", file: "variables.scss", line: 343, kind: Kind::Color, value: "#1bd96a40" },
    Row { token: "--color-link", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-link-active", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-link-hover", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-orange", file: "variables.scss", line: 258, kind: Kind::Color, value: "#ffa347" },
    Row { token: "--color-orange-100", file: "variables.scss", line: 255, kind: Kind::Color, value: "#ffefd4" },
    Row { token: "--color-orange-200", file: "variables.scss", line: 256, kind: Kind::Color, value: "#ffdba8" },
    Row { token: "--color-orange-300", file: "variables.scss", line: 257, kind: Kind::Color, value: "#ffc171" },
    Row { token: "--color-orange-400", file: "variables.scss", line: 258, kind: Kind::Color, value: "#ffa347" },
    Row { token: "--color-orange-50", file: "variables.scss", line: 254, kind: Kind::Color, value: "#fff8ed" },
    Row { token: "--color-orange-500", file: "variables.scss", line: 259, kind: Kind::Color, value: "#fe7e11" },
    Row { token: "--color-orange-600", file: "variables.scss", line: 260, kind: Kind::Color, value: "#ef6307" },
    Row { token: "--color-orange-700", file: "variables.scss", line: 261, kind: Kind::Color, value: "#c64808" },
    Row { token: "--color-orange-800", file: "variables.scss", line: 262, kind: Kind::Color, value: "#9d3a0f" },
    Row { token: "--color-orange-900", file: "variables.scss", line: 263, kind: Kind::Color, value: "#7e3110" },
    Row { token: "--color-orange-950", file: "variables.scss", line: 264, kind: Kind::Color, value: "#441606" },
    Row { token: "--color-orange-bg", file: "variables.scss", line: 349, kind: Kind::Color, value: "#ffa34733" },
    Row { token: "--color-orange-highlight", file: "variables.scss", line: 342, kind: Kind::Color, value: "#ffa34740" },
    Row { token: "--color-platform-bta-babric", file: "variables.scss", line: 404, kind: Kind::Color, value: "#72cc4a" },
    Row { token: "--color-platform-bukkit", file: "variables.scss", line: 394, kind: Kind::Color, value: "#f6af7b" },
    Row { token: "--color-platform-bungeecord", file: "variables.scss", line: 395, kind: Kind::Color, value: "#d2c080" },
    Row { token: "--color-platform-fabric", file: "variables.scss", line: 389, kind: Kind::Color, value: "#dbb69b" },
    Row { token: "--color-platform-folia", file: "variables.scss", line: 396, kind: Kind::Color, value: "#a5e388" },
    Row { token: "--color-platform-forge", file: "variables.scss", line: 391, kind: Kind::Color, value: "#959eef" },
    Row { token: "--color-platform-liteloader", file: "variables.scss", line: 393, kind: Kind::Color, value: "#7ab0ee" },
    Row { token: "--color-platform-neoforge", file: "variables.scss", line: 392, kind: Kind::Color, value: "#f99e6b" },
    Row { token: "--color-platform-nilloader", file: "variables.scss", line: 405, kind: Kind::Color, value: "#f45e9a" },
    Row { token: "--color-platform-ornithe", file: "variables.scss", line: 403, kind: Kind::Color, value: "#87c7ff" },
    Row { token: "--color-platform-paper", file: "variables.scss", line: 397, kind: Kind::Color, value: "#eeaaaa" },
    Row { token: "--color-platform-purpur", file: "variables.scss", line: 398, kind: Kind::Color, value: "#c3abf7" },
    Row { token: "--color-platform-quilt", file: "variables.scss", line: 390, kind: Kind::Color, value: "#c796f9" },
    Row { token: "--color-platform-spigot", file: "variables.scss", line: 399, kind: Kind::Color, value: "#f1cc84" },
    Row { token: "--color-platform-sponge", file: "variables.scss", line: 402, kind: Kind::Color, value: "#f9e580" },
    Row { token: "--color-platform-velocity", file: "variables.scss", line: 400, kind: Kind::Color, value: "#83d5ef" },
    Row { token: "--color-platform-waterfall", file: "variables.scss", line: 401, kind: Kind::Color, value: "#78a4fb" },
    Row { token: "--color-purple", file: "variables.scss", line: 297, kind: Kind::Color, value: "#c78aff" },
    Row { token: "--color-purple-100", file: "variables.scss", line: 294, kind: Kind::Color, value: "#f4e7ff" },
    Row { token: "--color-purple-200", file: "variables.scss", line: 295, kind: Kind::Color, value: "#ead4ff" },
    Row { token: "--color-purple-300", file: "variables.scss", line: 296, kind: Kind::Color, value: "#dab2ff" },
    Row { token: "--color-purple-400", file: "variables.scss", line: 297, kind: Kind::Color, value: "#c78aff" },
    Row { token: "--color-purple-50", file: "variables.scss", line: 293, kind: Kind::Color, value: "#faf5ff" },
    Row { token: "--color-purple-500", file: "variables.scss", line: 298, kind: Kind::Color, value: "#ac51fb" },
    Row { token: "--color-purple-600", file: "variables.scss", line: 299, kind: Kind::Color, value: "#972eef" },
    Row { token: "--color-purple-700", file: "variables.scss", line: 300, kind: Kind::Color, value: "#821ed2" },
    Row { token: "--color-purple-800", file: "variables.scss", line: 301, kind: Kind::Color, value: "#6e1eab" },
    Row { token: "--color-purple-900", file: "variables.scss", line: 302, kind: Kind::Color, value: "#5a198a" },
    Row { token: "--color-purple-950", file: "variables.scss", line: 303, kind: Kind::Color, value: "#3d0566" },
    Row { token: "--color-purple-bg", file: "variables.scss", line: 352, kind: Kind::Color, value: "#c78aff33" },
    Row { token: "--color-purple-highlight", file: "variables.scss", line: 345, kind: Kind::Color, value: "#c78aff40" },
    Row { token: "--color-raised-bg", file: "variables.scss", line: 237, kind: Kind::Color, value: "#27292e" },
    Row { token: "--color-red", file: "variables.scss", line: 246, kind: Kind::Color, value: "#ff496e" },
    Row { token: "--color-red-100", file: "variables.scss", line: 242, kind: Kind::Color, value: "#ffe2e6" },
    Row { token: "--color-red-200", file: "variables.scss", line: 243, kind: Kind::Color, value: "#ffcad3" },
    Row { token: "--color-red-300", file: "variables.scss", line: 244, kind: Kind::Color, value: "#ff9fae" },
    Row { token: "--color-red-400", file: "variables.scss", line: 245, kind: Kind::Color, value: "#ff6984" },
    Row { token: "--color-red-50", file: "variables.scss", line: 241, kind: Kind::Color, value: "#fff0f1" },
    Row { token: "--color-red-500", file: "variables.scss", line: 246, kind: Kind::Color, value: "#ff496e" },
    Row { token: "--color-red-600", file: "variables.scss", line: 247, kind: Kind::Color, value: "#ed1148" },
    Row { token: "--color-red-700", file: "variables.scss", line: 248, kind: Kind::Color, value: "#c8083d" },
    Row { token: "--color-red-800", file: "variables.scss", line: 249, kind: Kind::Color, value: "#a8093a" },
    Row { token: "--color-red-900", file: "variables.scss", line: 250, kind: Kind::Color, value: "#8f0c38" },
    Row { token: "--color-red-950", file: "variables.scss", line: 251, kind: Kind::Color, value: "#50011a" },
    Row { token: "--color-red-bg", file: "variables.scss", line: 348, kind: Kind::Color, value: "#ff496e33" },
    Row { token: "--color-red-highlight", file: "variables.scss", line: 341, kind: Kind::Color, value: "#ff496e40" },
    Row { token: "--color-scrollbar", file: "variables.scss", line: 239, kind: Kind::Color, value: "#42444a" },
    Row { token: "--color-secondary", file: "variables.scss", line: 321, kind: Kind::Color, value: "#96a2b0" },
    Row { token: "--color-super-raised-bg", file: "variables.scss", line: 238, kind: Kind::Color, value: "#34363c" },
    Row { token: "--color-text-default", file: "variables.scss", line: 320, kind: Kind::Color, value: "#b0bac5" },
    Row { token: "--color-text-primary", file: "variables.scss", line: 319, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--color-text-tertiary", file: "variables.scss", line: 321, kind: Kind::Color, value: "#96a2b0" },
    Row { token: "--color-tooltip-bg", file: "variables.scss", line: 237, kind: Kind::Color, value: "#27292e" },
    Row { token: "--color-tooltip-text", file: "variables.scss", line: 319, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--dark-color-base", file: "variables.scss", line: 192, kind: Kind::Color, value: "#b0bac5" },
    Row { token: "--dark-color-contrast", file: "variables.scss", line: 193, kind: Kind::Color, value: "#ecf9fb" },
    Row { token: "--font-size-2xl", file: "defaults.scss", line: 30, kind: Kind::Length, value: "32" },
    Row { token: "--font-size-3xl", file: "defaults.scss", line: 31, kind: Kind::Length, value: "48" },
    Row { token: "--font-size-lg", file: "defaults.scss", line: 28, kind: Kind::Length, value: "20" },
    Row { token: "--font-size-md", file: "defaults.scss", line: 27, kind: Kind::Length, value: "18" },
    Row { token: "--font-size-nm", file: "defaults.scss", line: 26, kind: Kind::Length, value: "16" },
    Row { token: "--font-size-sm", file: "defaults.scss", line: 25, kind: Kind::Length, value: "14" },
    Row { token: "--font-size-xl", file: "defaults.scss", line: 29, kind: Kind::Length, value: "24" },
    Row { token: "--font-size-xs", file: "defaults.scss", line: 24, kind: Kind::Length, value: "12" },
    Row { token: "--font-size-xxs", file: "defaults.scss", line: 23, kind: Kind::Length, value: "10" },
    Row { token: "--font-standard", file: "defaults.scss", line: 12, kind: Kind::Text, value: "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Oxygen, Ubuntu, Roboto, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif" },
    Row { token: "--font-weight-bold", file: "defaults.scss", line: 36, kind: Kind::Number, value: "700" },
    Row { token: "--font-weight-extrabold", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--font-weight-heading", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--font-weight-medium", file: "defaults.scss", line: 35, kind: Kind::Number, value: "500" },
    Row { token: "--font-weight-regular", file: "defaults.scss", line: 34, kind: Kind::Number, value: "400" },
    Row { token: "--font-weight-text", file: "defaults.scss", line: 35, kind: Kind::Number, value: "500" },
    Row { token: "--font-weight-title", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--gap-lg", file: "variables.scss", line: 198, kind: Kind::Length, value: "16" },
    Row { token: "--gap-md", file: "variables.scss", line: 197, kind: Kind::Length, value: "12" },
    Row { token: "--gap-sm", file: "variables.scss", line: 196, kind: Kind::Length, value: "8" },
    Row { token: "--gap-xl", file: "variables.scss", line: 199, kind: Kind::Length, value: "24" },
    Row { token: "--gap-xs", file: "variables.scss", line: 195, kind: Kind::Length, value: "4" },
    Row { token: "--hover-brightness", file: "variables.scss", line: 407, kind: Kind::Number, value: "1.25" },
    Row { token: "--loading-bar-gradient", file: "variables.scss", line: 381, kind: Kind::Text, value: "linear-gradient(to right, var(--color-brand) 0%, #1ffa9a 100%)" },
    Row { token: "--mono-font", file: "defaults.scss", line: 15, kind: Kind::Text, value: "ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace" },
    Row { token: "--radius-lg", file: "variables.scss", line: 204, kind: Kind::Length, value: "16" },
    Row { token: "--radius-max", file: "variables.scss", line: 206, kind: Kind::Length, value: "999999999" },
    Row { token: "--radius-md", file: "variables.scss", line: 203, kind: Kind::Length, value: "12" },
    Row { token: "--radius-sm", file: "variables.scss", line: 202, kind: Kind::Length, value: "8" },
    Row { token: "--radius-xl", file: "variables.scss", line: 205, kind: Kind::Length, value: "20" },
    Row { token: "--radius-xs", file: "variables.scss", line: 201, kind: Kind::Length, value: "4" },
    Row { token: "--shadow-button", file: "variables.scss", line: 220, kind: Kind::Text, value: "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.15)" },
    Row { token: "--shadow-card", file: "variables.scss", line: 368, kind: Kind::Text, value: "rgba(0, 0, 0, 0.25) 0px 2px 4px 0px" },
    Row { token: "--shadow-floating", file: "variables.scss", line: 364, kind: Kind::Text, value: "hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0.1) 0px 4px 6px -1px, rgba(0, 0, 0, 0.06) 0px 2px 4px -1px" },
    Row { token: "--shadow-inset", file: "variables.scss", line: 359, kind: Kind::Text, value: "inset 0px -2px 2px hsla(221, 39%, 11%, 0.05)" },
    Row { token: "--shadow-inset-lg", file: "variables.scss", line: 358, kind: Kind::Text, value: "inset 0px -2px 2px hsla(221, 39%, 11%, 0.1)" },
    Row { token: "--shadow-inset-sm", file: "variables.scss", line: 360, kind: Kind::Text, value: "inset 0px -1px 1px hsla(221, 39%, 11%, 0.25)" },
    Row { token: "--shadow-raised", file: "variables.scss", line: 363, kind: Kind::Text, value: "0px -2px 4px hsla(221, 39%, 11%, 0.1)" },
    Row { token: "--shadow-raised-lg", file: "variables.scss", line: 362, kind: Kind::Text, value: "0px 2px 4px hsla(221, 39%, 11%, 0.2)" },
    Row { token: "--splash-cube-blend", file: "variables.scss", line: 387, kind: Kind::Text, value: "normal" },
    Row { token: "--splash-cube-opacity", file: "variables.scss", line: 386, kind: Kind::Number, value: "0.8" },
    Row { token: "--splash-overlay", file: "variables.scss", line: 385, kind: Kind::Color, value: "#16181ca3" },
    Row { token: "--splash-tint-bottom", file: "variables.scss", line: 384, kind: Kind::Color, value: "#11232b80" },
    Row { token: "--splash-tint-top", file: "variables.scss", line: 383, kind: Kind::Color, value: "#42835c46" },
    Row { token: "--surface-1", file: "variables.scss", line: 233, kind: Kind::Color, value: "#16181c" },
    Row { token: "--surface-1-5", file: "variables.scss", line: 234, kind: Kind::Color, value: "#1a1c20" },
    Row { token: "--surface-2", file: "variables.scss", line: 235, kind: Kind::Color, value: "#1d1f23" },
    Row { token: "--surface-2-5", file: "variables.scss", line: 236, kind: Kind::Color, value: "#222429" },
    Row { token: "--surface-3", file: "variables.scss", line: 237, kind: Kind::Color, value: "#27292e" },
    Row { token: "--surface-4", file: "variables.scss", line: 238, kind: Kind::Color, value: "#34363c" },
    Row { token: "--surface-5", file: "variables.scss", line: 239, kind: Kind::Color, value: "#42444a" },
];

pub const OLED: &[Row] = &[
    Row { token: "--brand-gradient-bg", file: "variables.scss", line: 422, kind: Kind::Gradient, value: "#16423326@0,#3789491a@100" },
    Row { token: "--brand-gradient-border", file: "variables.scss", line: 373, kind: Kind::Color, value: "#9bffa014" },
    Row { token: "--brand-gradient-button", file: "variables.scss", line: 372, kind: Kind::Color, value: "#ffffff14" },
    Row { token: "--brand-gradient-fade-out-color", file: "variables.scss", line: 374, kind: Kind::Text, value: "linear-gradient(to bottom, rgba(24, 30, 31, 0), #171d1e 80%)" },
    Row { token: "--brand-gradient-strong-bg", file: "variables.scss", line: 427, kind: Kind::Gradient, value: "#09120e99@10,#131f1780@100" },
    Row { token: "--color-accent-contrast", file: "variables.scss", line: 339, kind: Kind::Color, value: "#000000" },
    Row { token: "--color-ad", file: "variables.scss", line: 420, kind: Kind::Color, value: "#0d1828" },
    Row { token: "--color-ad-contrast", file: "variables.scss", line: 213, kind: Kind::Color, value: "#000000" },
    Row { token: "--color-ad-highlight", file: "variables.scss", line: 297, kind: Kind::Color, value: "#c78aff" },
    Row { token: "--color-ad-raised", file: "variables.scss", line: 212, kind: Kind::Color, value: "#be8cf380" },
    Row { token: "--color-base", file: "variables.scss", line: 320, kind: Kind::Color, value: "#b0bac5" },
    Row { token: "--color-bg", file: "variables.scss", line: 412, kind: Kind::Color, value: "#000000" },
    Row { token: "--color-blue", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-blue-100", file: "variables.scss", line: 281, kind: Kind::Color, value: "#daeaff" },
    Row { token: "--color-blue-200", file: "variables.scss", line: 282, kind: Kind::Color, value: "#bddaff" },
    Row { token: "--color-blue-300", file: "variables.scss", line: 283, kind: Kind::Color, value: "#90c4ff" },
    Row { token: "--color-blue-400", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-blue-50", file: "variables.scss", line: 280, kind: Kind::Color, value: "#eef6ff" },
    Row { token: "--color-blue-500", file: "variables.scss", line: 285, kind: Kind::Color, value: "#357ffc" },
    Row { token: "--color-blue-600", file: "variables.scss", line: 286, kind: Kind::Color, value: "#1f5ff1" },
    Row { token: "--color-blue-700", file: "variables.scss", line: 287, kind: Kind::Color, value: "#1749de" },
    Row { token: "--color-blue-800", file: "variables.scss", line: 288, kind: Kind::Color, value: "#193cb4" },
    Row { token: "--color-blue-900", file: "variables.scss", line: 289, kind: Kind::Color, value: "#1a378e" },
    Row { token: "--color-blue-950", file: "variables.scss", line: 290, kind: Kind::Color, value: "#152356" },
    Row { token: "--color-blue-bg", file: "variables.scss", line: 351, kind: Kind::Color, value: "#4f9cff33" },
    Row { token: "--color-blue-highlight", file: "variables.scss", line: 344, kind: Kind::Color, value: "#4f9cff40" },
    Row { token: "--color-brand", file: "variables.scss", line: 272, kind: Kind::Color, value: "#1bd96a" },
    Row { token: "--color-brand-highlight", file: "variables.scss", line: 355, kind: Kind::Color, value: "#1bd96a40" },
    Row { token: "--color-brand-shadow", file: "variables.scss", line: 356, kind: Kind::Color, value: "#1bd96ab3" },
    Row { token: "--color-button-bg", file: "variables.scss", line: 417, kind: Kind::Color, value: "#1b1b20" },
    Row { token: "--color-button-bg-selected", file: "variables.scss", line: 355, kind: Kind::Color, value: "#1bd96a40" },
    Row { token: "--color-button-border", file: "variables.scss", line: 330, kind: Kind::Color, value: "#c1bed11f" },
    Row { token: "--color-button-text-selected", file: "variables.scss", line: 272, kind: Kind::Color, value: "#1bd96a" },
    Row { token: "--color-contrast", file: "variables.scss", line: 319, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--color-divider", file: "variables.scss", line: 417, kind: Kind::Color, value: "#1b1b20" },
    Row { token: "--color-divider-dark", file: "variables.scss", line: 334, kind: Kind::Color, value: "#646c75" },
    Row { token: "--color-focus-ring", file: "variables.scss", line: 222, kind: Kind::Color, value: "#ea80ff" },
    Row { token: "--color-gradient-button-bg", file: "variables.scss", line: 433, kind: Kind::Gradient, value: "#1b1b20@0,#25262b@100" },
    Row { token: "--color-gray", file: "variables.scss", line: 311, kind: Kind::Color, value: "#9fa4b3" },
    Row { token: "--color-gray-100", file: "variables.scss", line: 307, kind: Kind::Color, value: "#edeff2" },
    Row { token: "--color-gray-200", file: "variables.scss", line: 308, kind: Kind::Color, value: "#dfe2e6" },
    Row { token: "--color-gray-300", file: "variables.scss", line: 309, kind: Kind::Color, value: "#cad0d7" },
    Row { token: "--color-gray-400", file: "variables.scss", line: 310, kind: Kind::Color, value: "#b4bac5" },
    Row { token: "--color-gray-50", file: "variables.scss", line: 306, kind: Kind::Color, value: "#f5f7f8" },
    Row { token: "--color-gray-500", file: "variables.scss", line: 311, kind: Kind::Color, value: "#9fa4b3" },
    Row { token: "--color-gray-600", file: "variables.scss", line: 312, kind: Kind::Color, value: "#8a8da1" },
    Row { token: "--color-gray-700", file: "variables.scss", line: 313, kind: Kind::Color, value: "#777b8b" },
    Row { token: "--color-gray-800", file: "variables.scss", line: 314, kind: Kind::Color, value: "#616472" },
    Row { token: "--color-gray-900", file: "variables.scss", line: 315, kind: Kind::Color, value: "#52555d" },
    Row { token: "--color-gray-950", file: "variables.scss", line: 316, kind: Kind::Color, value: "#303136" },
    Row { token: "--color-gray-highlight", file: "variables.scss", line: 346, kind: Kind::Color, value: "#9fa4b340" },
    Row { token: "--color-green", file: "variables.scss", line: 272, kind: Kind::Color, value: "#1bd96a" },
    Row { token: "--color-green-100", file: "variables.scss", line: 268, kind: Kind::Color, value: "#dafee8" },
    Row { token: "--color-green-200", file: "variables.scss", line: 269, kind: Kind::Color, value: "#b8fad2" },
    Row { token: "--color-green-300", file: "variables.scss", line: 270, kind: Kind::Color, value: "#81f4af" },
    Row { token: "--color-green-400", file: "variables.scss", line: 271, kind: Kind::Color, value: "#42e686" },
    Row { token: "--color-green-50", file: "variables.scss", line: 267, kind: Kind::Color, value: "#effef5" },
    Row { token: "--color-green-500", file: "variables.scss", line: 272, kind: Kind::Color, value: "#1bd96a" },
    Row { token: "--color-green-600", file: "variables.scss", line: 273, kind: Kind::Color, value: "#0faa4f" },
    Row { token: "--color-green-700", file: "variables.scss", line: 274, kind: Kind::Color, value: "#0f8642" },
    Row { token: "--color-green-800", file: "variables.scss", line: 275, kind: Kind::Color, value: "#126937" },
    Row { token: "--color-green-900", file: "variables.scss", line: 276, kind: Kind::Color, value: "#11562f" },
    Row { token: "--color-green-950", file: "variables.scss", line: 277, kind: Kind::Color, value: "#033018" },
    Row { token: "--color-green-bg", file: "variables.scss", line: 350, kind: Kind::Color, value: "#1bd96a33" },
    Row { token: "--color-green-highlight", file: "variables.scss", line: 343, kind: Kind::Color, value: "#1bd96a40" },
    Row { token: "--color-link", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-link-active", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-link-hover", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-orange", file: "variables.scss", line: 258, kind: Kind::Color, value: "#ffa347" },
    Row { token: "--color-orange-100", file: "variables.scss", line: 255, kind: Kind::Color, value: "#ffefd4" },
    Row { token: "--color-orange-200", file: "variables.scss", line: 256, kind: Kind::Color, value: "#ffdba8" },
    Row { token: "--color-orange-300", file: "variables.scss", line: 257, kind: Kind::Color, value: "#ffc171" },
    Row { token: "--color-orange-400", file: "variables.scss", line: 258, kind: Kind::Color, value: "#ffa347" },
    Row { token: "--color-orange-50", file: "variables.scss", line: 254, kind: Kind::Color, value: "#fff8ed" },
    Row { token: "--color-orange-500", file: "variables.scss", line: 259, kind: Kind::Color, value: "#fe7e11" },
    Row { token: "--color-orange-600", file: "variables.scss", line: 260, kind: Kind::Color, value: "#ef6307" },
    Row { token: "--color-orange-700", file: "variables.scss", line: 261, kind: Kind::Color, value: "#c64808" },
    Row { token: "--color-orange-800", file: "variables.scss", line: 262, kind: Kind::Color, value: "#9d3a0f" },
    Row { token: "--color-orange-900", file: "variables.scss", line: 263, kind: Kind::Color, value: "#7e3110" },
    Row { token: "--color-orange-950", file: "variables.scss", line: 264, kind: Kind::Color, value: "#441606" },
    Row { token: "--color-orange-bg", file: "variables.scss", line: 349, kind: Kind::Color, value: "#ffa34733" },
    Row { token: "--color-orange-highlight", file: "variables.scss", line: 342, kind: Kind::Color, value: "#ffa34740" },
    Row { token: "--color-platform-bta-babric", file: "variables.scss", line: 404, kind: Kind::Color, value: "#72cc4a" },
    Row { token: "--color-platform-bukkit", file: "variables.scss", line: 394, kind: Kind::Color, value: "#f6af7b" },
    Row { token: "--color-platform-bungeecord", file: "variables.scss", line: 395, kind: Kind::Color, value: "#d2c080" },
    Row { token: "--color-platform-fabric", file: "variables.scss", line: 389, kind: Kind::Color, value: "#dbb69b" },
    Row { token: "--color-platform-folia", file: "variables.scss", line: 396, kind: Kind::Color, value: "#a5e388" },
    Row { token: "--color-platform-forge", file: "variables.scss", line: 391, kind: Kind::Color, value: "#959eef" },
    Row { token: "--color-platform-liteloader", file: "variables.scss", line: 393, kind: Kind::Color, value: "#7ab0ee" },
    Row { token: "--color-platform-neoforge", file: "variables.scss", line: 392, kind: Kind::Color, value: "#f99e6b" },
    Row { token: "--color-platform-nilloader", file: "variables.scss", line: 405, kind: Kind::Color, value: "#f45e9a" },
    Row { token: "--color-platform-ornithe", file: "variables.scss", line: 403, kind: Kind::Color, value: "#87c7ff" },
    Row { token: "--color-platform-paper", file: "variables.scss", line: 397, kind: Kind::Color, value: "#eeaaaa" },
    Row { token: "--color-platform-purpur", file: "variables.scss", line: 398, kind: Kind::Color, value: "#c3abf7" },
    Row { token: "--color-platform-quilt", file: "variables.scss", line: 390, kind: Kind::Color, value: "#c796f9" },
    Row { token: "--color-platform-spigot", file: "variables.scss", line: 399, kind: Kind::Color, value: "#f1cc84" },
    Row { token: "--color-platform-sponge", file: "variables.scss", line: 402, kind: Kind::Color, value: "#f9e580" },
    Row { token: "--color-platform-velocity", file: "variables.scss", line: 400, kind: Kind::Color, value: "#83d5ef" },
    Row { token: "--color-platform-waterfall", file: "variables.scss", line: 401, kind: Kind::Color, value: "#78a4fb" },
    Row { token: "--color-purple", file: "variables.scss", line: 297, kind: Kind::Color, value: "#c78aff" },
    Row { token: "--color-purple-100", file: "variables.scss", line: 294, kind: Kind::Color, value: "#f4e7ff" },
    Row { token: "--color-purple-200", file: "variables.scss", line: 295, kind: Kind::Color, value: "#ead4ff" },
    Row { token: "--color-purple-300", file: "variables.scss", line: 296, kind: Kind::Color, value: "#dab2ff" },
    Row { token: "--color-purple-400", file: "variables.scss", line: 297, kind: Kind::Color, value: "#c78aff" },
    Row { token: "--color-purple-50", file: "variables.scss", line: 293, kind: Kind::Color, value: "#faf5ff" },
    Row { token: "--color-purple-500", file: "variables.scss", line: 298, kind: Kind::Color, value: "#ac51fb" },
    Row { token: "--color-purple-600", file: "variables.scss", line: 299, kind: Kind::Color, value: "#972eef" },
    Row { token: "--color-purple-700", file: "variables.scss", line: 300, kind: Kind::Color, value: "#821ed2" },
    Row { token: "--color-purple-800", file: "variables.scss", line: 301, kind: Kind::Color, value: "#6e1eab" },
    Row { token: "--color-purple-900", file: "variables.scss", line: 302, kind: Kind::Color, value: "#5a198a" },
    Row { token: "--color-purple-950", file: "variables.scss", line: 303, kind: Kind::Color, value: "#3d0566" },
    Row { token: "--color-purple-bg", file: "variables.scss", line: 352, kind: Kind::Color, value: "#c78aff33" },
    Row { token: "--color-purple-highlight", file: "variables.scss", line: 345, kind: Kind::Color, value: "#c78aff40" },
    Row { token: "--color-raised-bg", file: "variables.scss", line: 416, kind: Kind::Color, value: "#101013" },
    Row { token: "--color-red", file: "variables.scss", line: 246, kind: Kind::Color, value: "#ff496e" },
    Row { token: "--color-red-100", file: "variables.scss", line: 242, kind: Kind::Color, value: "#ffe2e6" },
    Row { token: "--color-red-200", file: "variables.scss", line: 243, kind: Kind::Color, value: "#ffcad3" },
    Row { token: "--color-red-300", file: "variables.scss", line: 244, kind: Kind::Color, value: "#ff9fae" },
    Row { token: "--color-red-400", file: "variables.scss", line: 245, kind: Kind::Color, value: "#ff6984" },
    Row { token: "--color-red-50", file: "variables.scss", line: 241, kind: Kind::Color, value: "#fff0f1" },
    Row { token: "--color-red-500", file: "variables.scss", line: 246, kind: Kind::Color, value: "#ff496e" },
    Row { token: "--color-red-600", file: "variables.scss", line: 247, kind: Kind::Color, value: "#ed1148" },
    Row { token: "--color-red-700", file: "variables.scss", line: 248, kind: Kind::Color, value: "#c8083d" },
    Row { token: "--color-red-800", file: "variables.scss", line: 249, kind: Kind::Color, value: "#a8093a" },
    Row { token: "--color-red-900", file: "variables.scss", line: 250, kind: Kind::Color, value: "#8f0c38" },
    Row { token: "--color-red-950", file: "variables.scss", line: 251, kind: Kind::Color, value: "#50011a" },
    Row { token: "--color-red-bg", file: "variables.scss", line: 348, kind: Kind::Color, value: "#ff496e33" },
    Row { token: "--color-red-highlight", file: "variables.scss", line: 341, kind: Kind::Color, value: "#ff496e40" },
    Row { token: "--color-scrollbar", file: "variables.scss", line: 418, kind: Kind::Color, value: "#25262b" },
    Row { token: "--color-secondary", file: "variables.scss", line: 321, kind: Kind::Color, value: "#96a2b0" },
    Row { token: "--color-super-raised-bg", file: "variables.scss", line: 417, kind: Kind::Color, value: "#1b1b20" },
    Row { token: "--color-text-default", file: "variables.scss", line: 320, kind: Kind::Color, value: "#b0bac5" },
    Row { token: "--color-text-primary", file: "variables.scss", line: 319, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--color-text-tertiary", file: "variables.scss", line: 321, kind: Kind::Color, value: "#96a2b0" },
    Row { token: "--color-tooltip-bg", file: "variables.scss", line: 416, kind: Kind::Color, value: "#101013" },
    Row { token: "--color-tooltip-text", file: "variables.scss", line: 319, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--dark-color-base", file: "variables.scss", line: 192, kind: Kind::Color, value: "#b0bac5" },
    Row { token: "--dark-color-contrast", file: "variables.scss", line: 193, kind: Kind::Color, value: "#ecf9fb" },
    Row { token: "--font-size-2xl", file: "defaults.scss", line: 30, kind: Kind::Length, value: "32" },
    Row { token: "--font-size-3xl", file: "defaults.scss", line: 31, kind: Kind::Length, value: "48" },
    Row { token: "--font-size-lg", file: "defaults.scss", line: 28, kind: Kind::Length, value: "20" },
    Row { token: "--font-size-md", file: "defaults.scss", line: 27, kind: Kind::Length, value: "18" },
    Row { token: "--font-size-nm", file: "defaults.scss", line: 26, kind: Kind::Length, value: "16" },
    Row { token: "--font-size-sm", file: "defaults.scss", line: 25, kind: Kind::Length, value: "14" },
    Row { token: "--font-size-xl", file: "defaults.scss", line: 29, kind: Kind::Length, value: "24" },
    Row { token: "--font-size-xs", file: "defaults.scss", line: 24, kind: Kind::Length, value: "12" },
    Row { token: "--font-size-xxs", file: "defaults.scss", line: 23, kind: Kind::Length, value: "10" },
    Row { token: "--font-standard", file: "defaults.scss", line: 12, kind: Kind::Text, value: "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Oxygen, Ubuntu, Roboto, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif" },
    Row { token: "--font-weight-bold", file: "defaults.scss", line: 36, kind: Kind::Number, value: "700" },
    Row { token: "--font-weight-extrabold", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--font-weight-heading", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--font-weight-medium", file: "defaults.scss", line: 35, kind: Kind::Number, value: "500" },
    Row { token: "--font-weight-regular", file: "defaults.scss", line: 34, kind: Kind::Number, value: "400" },
    Row { token: "--font-weight-text", file: "defaults.scss", line: 35, kind: Kind::Number, value: "500" },
    Row { token: "--font-weight-title", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--gap-lg", file: "variables.scss", line: 198, kind: Kind::Length, value: "16" },
    Row { token: "--gap-md", file: "variables.scss", line: 197, kind: Kind::Length, value: "12" },
    Row { token: "--gap-sm", file: "variables.scss", line: 196, kind: Kind::Length, value: "8" },
    Row { token: "--gap-xl", file: "variables.scss", line: 199, kind: Kind::Length, value: "24" },
    Row { token: "--gap-xs", file: "variables.scss", line: 195, kind: Kind::Length, value: "4" },
    Row { token: "--hover-brightness", file: "variables.scss", line: 407, kind: Kind::Number, value: "1.25" },
    Row { token: "--loading-bar-gradient", file: "variables.scss", line: 381, kind: Kind::Text, value: "linear-gradient(to right, var(--color-brand) 0%, #1ffa9a 100%)" },
    Row { token: "--mono-font", file: "defaults.scss", line: 15, kind: Kind::Text, value: "ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace" },
    Row { token: "--radius-lg", file: "variables.scss", line: 204, kind: Kind::Length, value: "16" },
    Row { token: "--radius-max", file: "variables.scss", line: 206, kind: Kind::Length, value: "999999999" },
    Row { token: "--radius-md", file: "variables.scss", line: 203, kind: Kind::Length, value: "12" },
    Row { token: "--radius-sm", file: "variables.scss", line: 202, kind: Kind::Length, value: "8" },
    Row { token: "--radius-xl", file: "variables.scss", line: 205, kind: Kind::Length, value: "20" },
    Row { token: "--radius-xs", file: "variables.scss", line: 201, kind: Kind::Length, value: "4" },
    Row { token: "--shadow-button", file: "variables.scss", line: 220, kind: Kind::Text, value: "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.15)" },
    Row { token: "--shadow-card", file: "variables.scss", line: 368, kind: Kind::Text, value: "rgba(0, 0, 0, 0.25) 0px 2px 4px 0px" },
    Row { token: "--shadow-floating", file: "variables.scss", line: 364, kind: Kind::Text, value: "hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0.1) 0px 4px 6px -1px, rgba(0, 0, 0, 0.06) 0px 2px 4px -1px" },
    Row { token: "--shadow-inset", file: "variables.scss", line: 359, kind: Kind::Text, value: "inset 0px -2px 2px hsla(221, 39%, 11%, 0.05)" },
    Row { token: "--shadow-inset-lg", file: "variables.scss", line: 358, kind: Kind::Text, value: "inset 0px -2px 2px hsla(221, 39%, 11%, 0.1)" },
    Row { token: "--shadow-inset-sm", file: "variables.scss", line: 360, kind: Kind::Text, value: "inset 0px -1px 1px hsla(221, 39%, 11%, 0.25)" },
    Row { token: "--shadow-raised", file: "variables.scss", line: 363, kind: Kind::Text, value: "0px -2px 4px hsla(221, 39%, 11%, 0.1)" },
    Row { token: "--shadow-raised-lg", file: "variables.scss", line: 362, kind: Kind::Text, value: "0px 2px 4px hsla(221, 39%, 11%, 0.2)" },
    Row { token: "--splash-cube-blend", file: "variables.scss", line: 387, kind: Kind::Text, value: "normal" },
    Row { token: "--splash-cube-opacity", file: "variables.scss", line: 386, kind: Kind::Number, value: "0.8" },
    Row { token: "--splash-overlay", file: "variables.scss", line: 385, kind: Kind::Color, value: "#16181ca3" },
    Row { token: "--splash-tint-bottom", file: "variables.scss", line: 384, kind: Kind::Color, value: "#11232b80" },
    Row { token: "--splash-tint-top", file: "variables.scss", line: 383, kind: Kind::Color, value: "#42835c46" },
    Row { token: "--surface-1", file: "variables.scss", line: 412, kind: Kind::Color, value: "#000000" },
    Row { token: "--surface-1-5", file: "variables.scss", line: 413, kind: Kind::Color, value: "#050506" },
    Row { token: "--surface-2", file: "variables.scss", line: 414, kind: Kind::Color, value: "#09090a" },
    Row { token: "--surface-2-5", file: "variables.scss", line: 415, kind: Kind::Color, value: "#0c0d11" },
    Row { token: "--surface-3", file: "variables.scss", line: 416, kind: Kind::Color, value: "#101013" },
    Row { token: "--surface-4", file: "variables.scss", line: 417, kind: Kind::Color, value: "#1b1b20" },
    Row { token: "--surface-5", file: "variables.scss", line: 418, kind: Kind::Color, value: "#25262b" },
];

pub const RETRO: &[Row] = &[
    Row { token: "--brand-gradient-bg", file: "variables.scss", line: 370, kind: Kind::Gradient, value: "#0e231333@0,#3789491a@100" },
    Row { token: "--brand-gradient-border", file: "variables.scss", line: 373, kind: Kind::Color, value: "#9bffa014" },
    Row { token: "--brand-gradient-button", file: "variables.scss", line: 372, kind: Kind::Color, value: "#ffffff14" },
    Row { token: "--brand-gradient-fade-out-color", file: "variables.scss", line: 374, kind: Kind::Text, value: "linear-gradient(to bottom, rgba(24, 30, 31, 0), #171d1e 80%)" },
    Row { token: "--brand-gradient-strong-bg", file: "variables.scss", line: 474, kind: Kind::Color, value: "#3a3b38" },
    Row { token: "--color-accent-contrast", file: "variables.scss", line: 454, kind: Kind::Color, value: "#ffffff" },
    Row { token: "--color-ad", file: "variables.scss", line: 453, kind: Kind::Color, value: "#25421e" },
    Row { token: "--color-ad-contrast", file: "variables.scss", line: 457, kind: Kind::Color, value: "#000000" },
    Row { token: "--color-ad-highlight", file: "variables.scss", line: 452, kind: Kind::Color, value: "#4d9227" },
    Row { token: "--color-ad-raised", file: "variables.scss", line: 452, kind: Kind::Color, value: "#4d9227" },
    Row { token: "--color-base", file: "variables.scss", line: 445, kind: Kind::Color, value: "#c3c4b3" },
    Row { token: "--color-bg", file: "variables.scss", line: 438, kind: Kind::Color, value: "#191917" },
    Row { token: "--color-blue", file: "variables.scss", line: 463, kind: Kind::Color, value: "#099fef" },
    Row { token: "--color-blue-100", file: "variables.scss", line: 281, kind: Kind::Color, value: "#daeaff" },
    Row { token: "--color-blue-200", file: "variables.scss", line: 282, kind: Kind::Color, value: "#bddaff" },
    Row { token: "--color-blue-300", file: "variables.scss", line: 283, kind: Kind::Color, value: "#90c4ff" },
    Row { token: "--color-blue-400", file: "variables.scss", line: 284, kind: Kind::Color, value: "#4f9cff" },
    Row { token: "--color-blue-50", file: "variables.scss", line: 280, kind: Kind::Color, value: "#eef6ff" },
    Row { token: "--color-blue-500", file: "variables.scss", line: 285, kind: Kind::Color, value: "#357ffc" },
    Row { token: "--color-blue-600", file: "variables.scss", line: 286, kind: Kind::Color, value: "#1f5ff1" },
    Row { token: "--color-blue-700", file: "variables.scss", line: 287, kind: Kind::Color, value: "#1749de" },
    Row { token: "--color-blue-800", file: "variables.scss", line: 288, kind: Kind::Color, value: "#193cb4" },
    Row { token: "--color-blue-900", file: "variables.scss", line: 289, kind: Kind::Color, value: "#1a378e" },
    Row { token: "--color-blue-950", file: "variables.scss", line: 290, kind: Kind::Color, value: "#152356" },
    Row { token: "--color-blue-bg", file: "variables.scss", line: 351, kind: Kind::Color, value: "#4f9cff33" },
    Row { token: "--color-blue-highlight", file: "variables.scss", line: 470, kind: Kind::Color, value: "#099fef40" },
    Row { token: "--color-brand", file: "variables.scss", line: 452, kind: Kind::Color, value: "#4d9227" },
    Row { token: "--color-brand-highlight", file: "variables.scss", line: 453, kind: Kind::Color, value: "#25421e" },
    Row { token: "--color-brand-shadow", file: "variables.scss", line: 356, kind: Kind::Color, value: "#1bd96ab3" },
    Row { token: "--color-button-bg", file: "variables.scss", line: 444, kind: Kind::Color, value: "#3a3b38" },
    Row { token: "--color-button-bg-selected", file: "variables.scss", line: 453, kind: Kind::Color, value: "#25421e" },
    Row { token: "--color-button-border", file: "variables.scss", line: 330, kind: Kind::Color, value: "#c1bed11f" },
    Row { token: "--color-button-text-selected", file: "variables.scss", line: 452, kind: Kind::Color, value: "#4d9227" },
    Row { token: "--color-contrast", file: "variables.scss", line: 447, kind: Kind::Color, value: "#e6e2d1" },
    Row { token: "--color-divider", file: "variables.scss", line: 444, kind: Kind::Color, value: "#3a3b38" },
    Row { token: "--color-divider-dark", file: "variables.scss", line: 334, kind: Kind::Color, value: "#646c75" },
    Row { token: "--color-focus-ring", file: "variables.scss", line: 222, kind: Kind::Color, value: "#ea80ff" },
    Row { token: "--color-gradient-button-bg", file: "variables.scss", line: 379, kind: Kind::Gradient, value: "#3a3d47@0,#33363d@100" },
    Row { token: "--color-gray", file: "variables.scss", line: 465, kind: Kind::Color, value: "#718096" },
    Row { token: "--color-gray-100", file: "variables.scss", line: 307, kind: Kind::Color, value: "#edeff2" },
    Row { token: "--color-gray-200", file: "variables.scss", line: 308, kind: Kind::Color, value: "#dfe2e6" },
    Row { token: "--color-gray-300", file: "variables.scss", line: 309, kind: Kind::Color, value: "#cad0d7" },
    Row { token: "--color-gray-400", file: "variables.scss", line: 310, kind: Kind::Color, value: "#b4bac5" },
    Row { token: "--color-gray-50", file: "variables.scss", line: 306, kind: Kind::Color, value: "#f5f7f8" },
    Row { token: "--color-gray-500", file: "variables.scss", line: 311, kind: Kind::Color, value: "#9fa4b3" },
    Row { token: "--color-gray-600", file: "variables.scss", line: 312, kind: Kind::Color, value: "#8a8da1" },
    Row { token: "--color-gray-700", file: "variables.scss", line: 313, kind: Kind::Color, value: "#777b8b" },
    Row { token: "--color-gray-800", file: "variables.scss", line: 314, kind: Kind::Color, value: "#616472" },
    Row { token: "--color-gray-900", file: "variables.scss", line: 315, kind: Kind::Color, value: "#52555d" },
    Row { token: "--color-gray-950", file: "variables.scss", line: 316, kind: Kind::Color, value: "#303136" },
    Row { token: "--color-gray-highlight", file: "variables.scss", line: 472, kind: Kind::Color, value: "#71809640" },
    Row { token: "--color-green", file: "variables.scss", line: 462, kind: Kind::Color, value: "#3cdb36" },
    Row { token: "--color-green-100", file: "variables.scss", line: 268, kind: Kind::Color, value: "#dafee8" },
    Row { token: "--color-green-200", file: "variables.scss", line: 269, kind: Kind::Color, value: "#b8fad2" },
    Row { token: "--color-green-300", file: "variables.scss", line: 270, kind: Kind::Color, value: "#81f4af" },
    Row { token: "--color-green-400", file: "variables.scss", line: 271, kind: Kind::Color, value: "#42e686" },
    Row { token: "--color-green-50", file: "variables.scss", line: 267, kind: Kind::Color, value: "#effef5" },
    Row { token: "--color-green-500", file: "variables.scss", line: 272, kind: Kind::Color, value: "#1bd96a" },
    Row { token: "--color-green-600", file: "variables.scss", line: 273, kind: Kind::Color, value: "#0faa4f" },
    Row { token: "--color-green-700", file: "variables.scss", line: 274, kind: Kind::Color, value: "#0f8642" },
    Row { token: "--color-green-800", file: "variables.scss", line: 275, kind: Kind::Color, value: "#126937" },
    Row { token: "--color-green-900", file: "variables.scss", line: 276, kind: Kind::Color, value: "#11562f" },
    Row { token: "--color-green-950", file: "variables.scss", line: 277, kind: Kind::Color, value: "#033018" },
    Row { token: "--color-green-bg", file: "variables.scss", line: 350, kind: Kind::Color, value: "#1bd96a33" },
    Row { token: "--color-green-highlight", file: "variables.scss", line: 469, kind: Kind::Color, value: "#3cdb3640" },
    Row { token: "--color-link", file: "variables.scss", line: 463, kind: Kind::Color, value: "#099fef" },
    Row { token: "--color-link-active", file: "variables.scss", line: 463, kind: Kind::Color, value: "#099fef" },
    Row { token: "--color-link-hover", file: "variables.scss", line: 463, kind: Kind::Color, value: "#099fef" },
    Row { token: "--color-orange", file: "variables.scss", line: 461, kind: Kind::Color, value: "#e88d0d" },
    Row { token: "--color-orange-100", file: "variables.scss", line: 255, kind: Kind::Color, value: "#ffefd4" },
    Row { token: "--color-orange-200", file: "variables.scss", line: 256, kind: Kind::Color, value: "#ffdba8" },
    Row { token: "--color-orange-300", file: "variables.scss", line: 257, kind: Kind::Color, value: "#ffc171" },
    Row { token: "--color-orange-400", file: "variables.scss", line: 258, kind: Kind::Color, value: "#ffa347" },
    Row { token: "--color-orange-50", file: "variables.scss", line: 254, kind: Kind::Color, value: "#fff8ed" },
    Row { token: "--color-orange-500", file: "variables.scss", line: 259, kind: Kind::Color, value: "#fe7e11" },
    Row { token: "--color-orange-600", file: "variables.scss", line: 260, kind: Kind::Color, value: "#ef6307" },
    Row { token: "--color-orange-700", file: "variables.scss", line: 261, kind: Kind::Color, value: "#c64808" },
    Row { token: "--color-orange-800", file: "variables.scss", line: 262, kind: Kind::Color, value: "#9d3a0f" },
    Row { token: "--color-orange-900", file: "variables.scss", line: 263, kind: Kind::Color, value: "#7e3110" },
    Row { token: "--color-orange-950", file: "variables.scss", line: 264, kind: Kind::Color, value: "#441606" },
    Row { token: "--color-orange-bg", file: "variables.scss", line: 349, kind: Kind::Color, value: "#ffa34733" },
    Row { token: "--color-orange-highlight", file: "variables.scss", line: 468, kind: Kind::Color, value: "#e88d0d40" },
    Row { token: "--color-platform-bta-babric", file: "variables.scss", line: 404, kind: Kind::Color, value: "#72cc4a" },
    Row { token: "--color-platform-bukkit", file: "variables.scss", line: 394, kind: Kind::Color, value: "#f6af7b" },
    Row { token: "--color-platform-bungeecord", file: "variables.scss", line: 395, kind: Kind::Color, value: "#d2c080" },
    Row { token: "--color-platform-fabric", file: "variables.scss", line: 389, kind: Kind::Color, value: "#dbb69b" },
    Row { token: "--color-platform-folia", file: "variables.scss", line: 396, kind: Kind::Color, value: "#a5e388" },
    Row { token: "--color-platform-forge", file: "variables.scss", line: 391, kind: Kind::Color, value: "#959eef" },
    Row { token: "--color-platform-liteloader", file: "variables.scss", line: 393, kind: Kind::Color, value: "#7ab0ee" },
    Row { token: "--color-platform-neoforge", file: "variables.scss", line: 392, kind: Kind::Color, value: "#f99e6b" },
    Row { token: "--color-platform-nilloader", file: "variables.scss", line: 405, kind: Kind::Color, value: "#f45e9a" },
    Row { token: "--color-platform-ornithe", file: "variables.scss", line: 403, kind: Kind::Color, value: "#87c7ff" },
    Row { token: "--color-platform-paper", file: "variables.scss", line: 397, kind: Kind::Color, value: "#eeaaaa" },
    Row { token: "--color-platform-purpur", file: "variables.scss", line: 398, kind: Kind::Color, value: "#c3abf7" },
    Row { token: "--color-platform-quilt", file: "variables.scss", line: 390, kind: Kind::Color, value: "#c796f9" },
    Row { token: "--color-platform-spigot", file: "variables.scss", line: 399, kind: Kind::Color, value: "#f1cc84" },
    Row { token: "--color-platform-sponge", file: "variables.scss", line: 402, kind: Kind::Color, value: "#f9e580" },
    Row { token: "--color-platform-velocity", file: "variables.scss", line: 400, kind: Kind::Color, value: "#83d5ef" },
    Row { token: "--color-platform-waterfall", file: "variables.scss", line: 401, kind: Kind::Color, value: "#78a4fb" },
    Row { token: "--color-purple", file: "variables.scss", line: 464, kind: Kind::Color, value: "#8b81e6" },
    Row { token: "--color-purple-100", file: "variables.scss", line: 294, kind: Kind::Color, value: "#f4e7ff" },
    Row { token: "--color-purple-200", file: "variables.scss", line: 295, kind: Kind::Color, value: "#ead4ff" },
    Row { token: "--color-purple-300", file: "variables.scss", line: 296, kind: Kind::Color, value: "#dab2ff" },
    Row { token: "--color-purple-400", file: "variables.scss", line: 297, kind: Kind::Color, value: "#c78aff" },
    Row { token: "--color-purple-50", file: "variables.scss", line: 293, kind: Kind::Color, value: "#faf5ff" },
    Row { token: "--color-purple-500", file: "variables.scss", line: 298, kind: Kind::Color, value: "#ac51fb" },
    Row { token: "--color-purple-600", file: "variables.scss", line: 299, kind: Kind::Color, value: "#972eef" },
    Row { token: "--color-purple-700", file: "variables.scss", line: 300, kind: Kind::Color, value: "#821ed2" },
    Row { token: "--color-purple-800", file: "variables.scss", line: 301, kind: Kind::Color, value: "#6e1eab" },
    Row { token: "--color-purple-900", file: "variables.scss", line: 302, kind: Kind::Color, value: "#5a198a" },
    Row { token: "--color-purple-950", file: "variables.scss", line: 303, kind: Kind::Color, value: "#3d0566" },
    Row { token: "--color-purple-bg", file: "variables.scss", line: 352, kind: Kind::Color, value: "#c78aff33" },
    Row { token: "--color-purple-highlight", file: "variables.scss", line: 471, kind: Kind::Color, value: "#8b81e640" },
    Row { token: "--color-raised-bg", file: "variables.scss", line: 441, kind: Kind::Color, value: "#232421" },
    Row { token: "--color-red", file: "variables.scss", line: 460, kind: Kind::Color, value: "#e8200d" },
    Row { token: "--color-red-100", file: "variables.scss", line: 242, kind: Kind::Color, value: "#ffe2e6" },
    Row { token: "--color-red-200", file: "variables.scss", line: 243, kind: Kind::Color, value: "#ffcad3" },
    Row { token: "--color-red-300", file: "variables.scss", line: 244, kind: Kind::Color, value: "#ff9fae" },
    Row { token: "--color-red-400", file: "variables.scss", line: 245, kind: Kind::Color, value: "#ff6984" },
    Row { token: "--color-red-50", file: "variables.scss", line: 241, kind: Kind::Color, value: "#fff0f1" },
    Row { token: "--color-red-500", file: "variables.scss", line: 246, kind: Kind::Color, value: "#ff496e" },
    Row { token: "--color-red-600", file: "variables.scss", line: 247, kind: Kind::Color, value: "#ed1148" },
    Row { token: "--color-red-700", file: "variables.scss", line: 248, kind: Kind::Color, value: "#c8083d" },
    Row { token: "--color-red-800", file: "variables.scss", line: 249, kind: Kind::Color, value: "#a8093a" },
    Row { token: "--color-red-900", file: "variables.scss", line: 250, kind: Kind::Color, value: "#8f0c38" },
    Row { token: "--color-red-950", file: "variables.scss", line: 251, kind: Kind::Color, value: "#50011a" },
    Row { token: "--color-red-bg", file: "variables.scss", line: 348, kind: Kind::Color, value: "#ff496e33" },
    Row { token: "--color-red-highlight", file: "variables.scss", line: 467, kind: Kind::Color, value: "#e8200d40" },
    Row { token: "--color-scrollbar", file: "variables.scss", line: 443, kind: Kind::Color, value: "#5a5c58" },
    Row { token: "--color-secondary", file: "variables.scss", line: 446, kind: Kind::Color, value: "#9b9e98" },
    Row { token: "--color-super-raised-bg", file: "variables.scss", line: 442, kind: Kind::Color, value: "#3a3b38" },
    Row { token: "--color-text-default", file: "variables.scss", line: 449, kind: Kind::Color, value: "#c3c4b3" },
    Row { token: "--color-text-primary", file: "variables.scss", line: 448, kind: Kind::Color, value: "#e6e2d1" },
    Row { token: "--color-text-tertiary", file: "variables.scss", line: 450, kind: Kind::Color, value: "#9b9e98" },
    Row { token: "--color-tooltip-bg", file: "variables.scss", line: 441, kind: Kind::Color, value: "#232421" },
    Row { token: "--color-tooltip-text", file: "variables.scss", line: 447, kind: Kind::Color, value: "#e6e2d1" },
    Row { token: "--dark-color-base", file: "variables.scss", line: 192, kind: Kind::Color, value: "#b0bac5" },
    Row { token: "--dark-color-contrast", file: "variables.scss", line: 193, kind: Kind::Color, value: "#ecf9fb" },
    Row { token: "--font-size-2xl", file: "defaults.scss", line: 30, kind: Kind::Length, value: "32" },
    Row { token: "--font-size-3xl", file: "defaults.scss", line: 31, kind: Kind::Length, value: "48" },
    Row { token: "--font-size-lg", file: "defaults.scss", line: 28, kind: Kind::Length, value: "20" },
    Row { token: "--font-size-md", file: "defaults.scss", line: 27, kind: Kind::Length, value: "18" },
    Row { token: "--font-size-nm", file: "defaults.scss", line: 26, kind: Kind::Length, value: "16" },
    Row { token: "--font-size-sm", file: "defaults.scss", line: 25, kind: Kind::Length, value: "14" },
    Row { token: "--font-size-xl", file: "defaults.scss", line: 29, kind: Kind::Length, value: "24" },
    Row { token: "--font-size-xs", file: "defaults.scss", line: 24, kind: Kind::Length, value: "12" },
    Row { token: "--font-size-xxs", file: "defaults.scss", line: 23, kind: Kind::Length, value: "10" },
    Row { token: "--font-standard", file: "defaults.scss", line: 12, kind: Kind::Text, value: "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Oxygen, Ubuntu, Roboto, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif" },
    Row { token: "--font-weight-bold", file: "defaults.scss", line: 36, kind: Kind::Number, value: "700" },
    Row { token: "--font-weight-extrabold", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--font-weight-heading", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--font-weight-medium", file: "defaults.scss", line: 35, kind: Kind::Number, value: "500" },
    Row { token: "--font-weight-regular", file: "defaults.scss", line: 34, kind: Kind::Number, value: "400" },
    Row { token: "--font-weight-text", file: "defaults.scss", line: 35, kind: Kind::Number, value: "500" },
    Row { token: "--font-weight-title", file: "defaults.scss", line: 37, kind: Kind::Number, value: "800" },
    Row { token: "--gap-lg", file: "variables.scss", line: 198, kind: Kind::Length, value: "16" },
    Row { token: "--gap-md", file: "variables.scss", line: 197, kind: Kind::Length, value: "12" },
    Row { token: "--gap-sm", file: "variables.scss", line: 196, kind: Kind::Length, value: "8" },
    Row { token: "--gap-xl", file: "variables.scss", line: 199, kind: Kind::Length, value: "24" },
    Row { token: "--gap-xs", file: "variables.scss", line: 195, kind: Kind::Length, value: "4" },
    Row { token: "--hover-brightness", file: "variables.scss", line: 407, kind: Kind::Number, value: "1.25" },
    Row { token: "--loading-bar-gradient", file: "variables.scss", line: 381, kind: Kind::Text, value: "linear-gradient(to right, var(--color-brand) 0%, #1ffa9a 100%)" },
    Row { token: "--mono-font", file: "defaults.scss", line: 15, kind: Kind::Text, value: "ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace" },
    Row { token: "--radius-lg", file: "variables.scss", line: 204, kind: Kind::Length, value: "16" },
    Row { token: "--radius-max", file: "variables.scss", line: 206, kind: Kind::Length, value: "999999999" },
    Row { token: "--radius-md", file: "variables.scss", line: 203, kind: Kind::Length, value: "12" },
    Row { token: "--radius-sm", file: "variables.scss", line: 202, kind: Kind::Length, value: "8" },
    Row { token: "--radius-xl", file: "variables.scss", line: 205, kind: Kind::Length, value: "20" },
    Row { token: "--radius-xs", file: "variables.scss", line: 201, kind: Kind::Length, value: "4" },
    Row { token: "--shadow-button", file: "variables.scss", line: 220, kind: Kind::Text, value: "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.15)" },
    Row { token: "--shadow-card", file: "variables.scss", line: 368, kind: Kind::Text, value: "rgba(0, 0, 0, 0.25) 0px 2px 4px 0px" },
    Row { token: "--shadow-floating", file: "variables.scss", line: 364, kind: Kind::Text, value: "hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0.1) 0px 4px 6px -1px, rgba(0, 0, 0, 0.06) 0px 2px 4px -1px" },
    Row { token: "--shadow-inset", file: "variables.scss", line: 359, kind: Kind::Text, value: "inset 0px -2px 2px hsla(221, 39%, 11%, 0.05)" },
    Row { token: "--shadow-inset-lg", file: "variables.scss", line: 358, kind: Kind::Text, value: "inset 0px -2px 2px hsla(221, 39%, 11%, 0.1)" },
    Row { token: "--shadow-inset-sm", file: "variables.scss", line: 360, kind: Kind::Text, value: "inset 0px -1px 1px hsla(221, 39%, 11%, 0.25)" },
    Row { token: "--shadow-raised", file: "variables.scss", line: 363, kind: Kind::Text, value: "0px -2px 4px hsla(221, 39%, 11%, 0.1)" },
    Row { token: "--shadow-raised-lg", file: "variables.scss", line: 362, kind: Kind::Text, value: "0px 2px 4px hsla(221, 39%, 11%, 0.2)" },
    Row { token: "--splash-cube-blend", file: "variables.scss", line: 387, kind: Kind::Text, value: "normal" },
    Row { token: "--splash-cube-opacity", file: "variables.scss", line: 386, kind: Kind::Number, value: "0.8" },
    Row { token: "--splash-overlay", file: "variables.scss", line: 385, kind: Kind::Color, value: "#16181ca3" },
    Row { token: "--splash-tint-bottom", file: "variables.scss", line: 384, kind: Kind::Color, value: "#11232b80" },
    Row { token: "--splash-tint-top", file: "variables.scss", line: 383, kind: Kind::Color, value: "#42835c46" },
    Row { token: "--surface-1", file: "variables.scss", line: 438, kind: Kind::Color, value: "#191917" },
    Row { token: "--surface-1-5", file: "variables.scss", line: 234, kind: Kind::Color, value: "#1a1c20" },
    Row { token: "--surface-2", file: "variables.scss", line: 439, kind: Kind::Color, value: "#161615" },
    Row { token: "--surface-2-5", file: "variables.scss", line: 440, kind: Kind::Color, value: "#3a3c3e" },
    Row { token: "--surface-3", file: "variables.scss", line: 441, kind: Kind::Color, value: "#232421" },
    Row { token: "--surface-4", file: "variables.scss", line: 442, kind: Kind::Color, value: "#3a3b38" },
    Row { token: "--surface-5", file: "variables.scss", line: 443, kind: Kind::Color, value: "#5a5c58" },
];
