//! The reference client's design system, compiled from its own stylesheets.
//!
//! **Generated by `tools/gen_theme.py`. Do not edit.**
//!
//! Everything in this file is a value read out of the Modrinth App's vendored
//! CSS -- its palette, its radii and gaps, its bare numbers, its cubic-bezier
//! curves, the text it cannot express as a scalar, and the motion it declares.
//! The tool resolves `@extend` and `var()` indirection the way the cascade
//! would, so a token here is the value a browser would paint, not a copy of
//! the line that set it.
//!
//! This exists because the shell used to carry a hand-written palette beside a
//! test-only table of transcribed values, and they could disagree -- they did.
//! One module, generated, is the point.
//!
//! Sources, at the commit pinned in `vendor/modrinth-app/UPSTREAM.md`: 
//! `vendor/modrinth-app/assets/styles/variables.scss` and the motion declared across 
//! `vendor/modrinth-app/`. Regenerate with `python tools/gen_theme.py`; the 
//! gate is `python tools/gen_theme.py --check`.

// Nothing paints from here yet: the shell that will is stage 2 of
// `docs/superpowers/specs/2026-09-24-modrinth-native-rewrite.md`, and the shell
// on screen today paints from `theme.rs`. An allow rather than `cfg(test)`,
// because unlike the receipt this replaces, this file is the intended runtime
// source and a test-only attribute would have to be undone to use it.
// Delete this line the day the last page paints from these tables.
#![allow(dead_code)]

use iced::Color;

/// Which of the reference's four looks a value is being asked for.
///
/// The order is the order the generated tables are indexed in, so the
/// discriminant of a variant is its column.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Theme {
    /// The light look (`.light-properties`).
    Light,
    /// The dark look (`.dark-mode`), the one the app opens in by default.
    Dark,
    /// `.oled-mode`: dark's surfaces taken to true black.
    Oled,
    /// `.retro-mode`: dark with a warmer, desaturated palette.
    Retro,
}

impl Theme {
    /// The column this theme's value sits in.
    const fn index(self) -> usize {
        self as usize
    }

    /// Every theme, for a gate that has to visit all of them.
    pub const ALL: &'static [Theme] = &[Theme::Light, Theme::Dark, Theme::Oled, Theme::Retro];
}

/// A colour the reference names, e.g. `Ink::Surface4` for `--surface-4`.
///
/// A variant is the token, camel-cased, and `--color-` is dropped because
/// the enum already says what it is: `--color-text-primary` reads as
/// `Ink::TextPrimary`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Ink {
    /// `--brand-gradient-border`
    BrandGradientBorder,
    /// `--brand-gradient-button`
    BrandGradientButton,
    /// `--color-accent-contrast`
    AccentContrast,
    /// `--color-ad`
    Ad,
    /// `--color-ad-contrast`
    AdContrast,
    /// `--color-ad-highlight`
    AdHighlight,
    /// `--color-ad-raised`
    AdRaised,
    /// `--color-base`
    Base,
    /// `--color-bg`
    Bg,
    /// `--color-blue`
    Blue,
    /// `--color-blue-100`
    Blue100,
    /// `--color-blue-200`
    Blue200,
    /// `--color-blue-300`
    Blue300,
    /// `--color-blue-400`
    Blue400,
    /// `--color-blue-50`
    Blue50,
    /// `--color-blue-500`
    Blue500,
    /// `--color-blue-600`
    Blue600,
    /// `--color-blue-700`
    Blue700,
    /// `--color-blue-800`
    Blue800,
    /// `--color-blue-900`
    Blue900,
    /// `--color-blue-950`
    Blue950,
    /// `--color-blue-bg`
    BlueBg,
    /// `--color-blue-highlight`
    BlueHighlight,
    /// `--color-brand`
    Brand,
    /// `--color-brand-highlight`
    ColorBrandHighlight,
    /// `--color-brand-shadow`
    BrandShadow,
    /// `--color-button-bg`
    ButtonBg,
    /// `--color-button-bg-selected`
    ButtonBgSelected,
    /// `--color-button-border`
    ButtonBorder,
    /// `--color-button-text-selected`
    ButtonTextSelected,
    /// `--color-contrast`
    Contrast,
    /// `--color-divider`
    Divider,
    /// `--color-divider-dark`
    DividerDark,
    /// `--color-focus-ring`
    FocusRing,
    /// `--color-gray`
    Gray,
    /// `--color-gray-100`
    Gray100,
    /// `--color-gray-200`
    Gray200,
    /// `--color-gray-300`
    Gray300,
    /// `--color-gray-400`
    Gray400,
    /// `--color-gray-50`
    Gray50,
    /// `--color-gray-500`
    Gray500,
    /// `--color-gray-600`
    Gray600,
    /// `--color-gray-700`
    Gray700,
    /// `--color-gray-800`
    Gray800,
    /// `--color-gray-900`
    Gray900,
    /// `--color-gray-950`
    Gray950,
    /// `--color-gray-highlight`
    GrayHighlight,
    /// `--color-green`
    Green,
    /// `--color-green-100`
    Green100,
    /// `--color-green-200`
    Green200,
    /// `--color-green-300`
    Green300,
    /// `--color-green-400`
    Green400,
    /// `--color-green-50`
    Green50,
    /// `--color-green-500`
    Green500,
    /// `--color-green-600`
    Green600,
    /// `--color-green-700`
    Green700,
    /// `--color-green-800`
    Green800,
    /// `--color-green-900`
    Green900,
    /// `--color-green-950`
    Green950,
    /// `--color-green-bg`
    GreenBg,
    /// `--color-green-highlight`
    GreenHighlight,
    /// `--color-link`
    Link,
    /// `--color-link-active`
    LinkActive,
    /// `--color-link-hover`
    LinkHover,
    /// `--color-orange`
    Orange,
    /// `--color-orange-100`
    Orange100,
    /// `--color-orange-200`
    Orange200,
    /// `--color-orange-300`
    Orange300,
    /// `--color-orange-400`
    Orange400,
    /// `--color-orange-50`
    Orange50,
    /// `--color-orange-500`
    Orange500,
    /// `--color-orange-600`
    Orange600,
    /// `--color-orange-700`
    Orange700,
    /// `--color-orange-800`
    Orange800,
    /// `--color-orange-900`
    Orange900,
    /// `--color-orange-950`
    Orange950,
    /// `--color-orange-bg`
    OrangeBg,
    /// `--color-orange-highlight`
    OrangeHighlight,
    /// `--color-platform-bta-babric`
    PlatformBtaBabric,
    /// `--color-platform-bukkit`
    PlatformBukkit,
    /// `--color-platform-bungeecord`
    PlatformBungeecord,
    /// `--color-platform-fabric`
    PlatformFabric,
    /// `--color-platform-folia`
    PlatformFolia,
    /// `--color-platform-forge`
    PlatformForge,
    /// `--color-platform-liteloader`
    PlatformLiteloader,
    /// `--color-platform-neoforge`
    PlatformNeoforge,
    /// `--color-platform-nilloader`
    PlatformNilloader,
    /// `--color-platform-ornithe`
    PlatformOrnithe,
    /// `--color-platform-paper`
    PlatformPaper,
    /// `--color-platform-purpur`
    PlatformPurpur,
    /// `--color-platform-quilt`
    PlatformQuilt,
    /// `--color-platform-spigot`
    PlatformSpigot,
    /// `--color-platform-sponge`
    PlatformSponge,
    /// `--color-platform-velocity`
    PlatformVelocity,
    /// `--color-platform-waterfall`
    PlatformWaterfall,
    /// `--color-purple`
    Purple,
    /// `--color-purple-100`
    Purple100,
    /// `--color-purple-200`
    Purple200,
    /// `--color-purple-300`
    Purple300,
    /// `--color-purple-400`
    Purple400,
    /// `--color-purple-50`
    Purple50,
    /// `--color-purple-500`
    Purple500,
    /// `--color-purple-600`
    Purple600,
    /// `--color-purple-700`
    Purple700,
    /// `--color-purple-800`
    Purple800,
    /// `--color-purple-900`
    Purple900,
    /// `--color-purple-950`
    Purple950,
    /// `--color-purple-bg`
    PurpleBg,
    /// `--color-purple-highlight`
    PurpleHighlight,
    /// `--color-raised-bg`
    RaisedBg,
    /// `--color-red`
    Red,
    /// `--color-red-100`
    Red100,
    /// `--color-red-200`
    Red200,
    /// `--color-red-300`
    Red300,
    /// `--color-red-400`
    Red400,
    /// `--color-red-50`
    Red50,
    /// `--color-red-500`
    Red500,
    /// `--color-red-600`
    Red600,
    /// `--color-red-700`
    Red700,
    /// `--color-red-800`
    Red800,
    /// `--color-red-900`
    Red900,
    /// `--color-red-950`
    Red950,
    /// `--color-red-bg`
    RedBg,
    /// `--color-red-highlight`
    RedHighlight,
    /// `--color-scrollbar`
    Scrollbar,
    /// `--color-secondary`
    Secondary,
    /// `--color-super-raised-bg`
    SuperRaisedBg,
    /// `--color-text-default`
    TextDefault,
    /// `--color-text-primary`
    TextPrimary,
    /// `--color-text-tertiary`
    TextTertiary,
    /// `--color-tooltip-bg`
    TooltipBg,
    /// `--color-tooltip-text`
    TooltipText,
    /// `--dark-color-base`
    DarkColorBase,
    /// `--dark-color-contrast`
    DarkColorContrast,
    /// `--splash-overlay`
    SplashOverlay,
    /// `--splash-tint-bottom`
    SplashTintBottom,
    /// `--splash-tint-top`
    SplashTintTop,
    /// `--surface-1`
    Surface1,
    /// `--surface-1-5`
    Surface15,
    /// `--surface-2`
    Surface2,
    /// `--surface-2-5`
    Surface25,
    /// `--surface-3`
    Surface3,
    /// `--surface-4`
    Surface4,
    /// `--surface-5`
    Surface5,
}

/// Every colour token, in the order the table below is sorted in.
pub const ALL_INK: &[Ink] = &[
    Ink::BrandGradientBorder,
    Ink::BrandGradientButton,
    Ink::AccentContrast,
    Ink::Ad,
    Ink::AdContrast,
    Ink::AdHighlight,
    Ink::AdRaised,
    Ink::Base,
    Ink::Bg,
    Ink::Blue,
    Ink::Blue100,
    Ink::Blue200,
    Ink::Blue300,
    Ink::Blue400,
    Ink::Blue50,
    Ink::Blue500,
    Ink::Blue600,
    Ink::Blue700,
    Ink::Blue800,
    Ink::Blue900,
    Ink::Blue950,
    Ink::BlueBg,
    Ink::BlueHighlight,
    Ink::Brand,
    Ink::ColorBrandHighlight,
    Ink::BrandShadow,
    Ink::ButtonBg,
    Ink::ButtonBgSelected,
    Ink::ButtonBorder,
    Ink::ButtonTextSelected,
    Ink::Contrast,
    Ink::Divider,
    Ink::DividerDark,
    Ink::FocusRing,
    Ink::Gray,
    Ink::Gray100,
    Ink::Gray200,
    Ink::Gray300,
    Ink::Gray400,
    Ink::Gray50,
    Ink::Gray500,
    Ink::Gray600,
    Ink::Gray700,
    Ink::Gray800,
    Ink::Gray900,
    Ink::Gray950,
    Ink::GrayHighlight,
    Ink::Green,
    Ink::Green100,
    Ink::Green200,
    Ink::Green300,
    Ink::Green400,
    Ink::Green50,
    Ink::Green500,
    Ink::Green600,
    Ink::Green700,
    Ink::Green800,
    Ink::Green900,
    Ink::Green950,
    Ink::GreenBg,
    Ink::GreenHighlight,
    Ink::Link,
    Ink::LinkActive,
    Ink::LinkHover,
    Ink::Orange,
    Ink::Orange100,
    Ink::Orange200,
    Ink::Orange300,
    Ink::Orange400,
    Ink::Orange50,
    Ink::Orange500,
    Ink::Orange600,
    Ink::Orange700,
    Ink::Orange800,
    Ink::Orange900,
    Ink::Orange950,
    Ink::OrangeBg,
    Ink::OrangeHighlight,
    Ink::PlatformBtaBabric,
    Ink::PlatformBukkit,
    Ink::PlatformBungeecord,
    Ink::PlatformFabric,
    Ink::PlatformFolia,
    Ink::PlatformForge,
    Ink::PlatformLiteloader,
    Ink::PlatformNeoforge,
    Ink::PlatformNilloader,
    Ink::PlatformOrnithe,
    Ink::PlatformPaper,
    Ink::PlatformPurpur,
    Ink::PlatformQuilt,
    Ink::PlatformSpigot,
    Ink::PlatformSponge,
    Ink::PlatformVelocity,
    Ink::PlatformWaterfall,
    Ink::Purple,
    Ink::Purple100,
    Ink::Purple200,
    Ink::Purple300,
    Ink::Purple400,
    Ink::Purple50,
    Ink::Purple500,
    Ink::Purple600,
    Ink::Purple700,
    Ink::Purple800,
    Ink::Purple900,
    Ink::Purple950,
    Ink::PurpleBg,
    Ink::PurpleHighlight,
    Ink::RaisedBg,
    Ink::Red,
    Ink::Red100,
    Ink::Red200,
    Ink::Red300,
    Ink::Red400,
    Ink::Red50,
    Ink::Red500,
    Ink::Red600,
    Ink::Red700,
    Ink::Red800,
    Ink::Red900,
    Ink::Red950,
    Ink::RedBg,
    Ink::RedHighlight,
    Ink::Scrollbar,
    Ink::Secondary,
    Ink::SuperRaisedBg,
    Ink::TextDefault,
    Ink::TextPrimary,
    Ink::TextTertiary,
    Ink::TooltipBg,
    Ink::TooltipText,
    Ink::DarkColorBase,
    Ink::DarkColorContrast,
    Ink::SplashOverlay,
    Ink::SplashTintBottom,
    Ink::SplashTintTop,
    Ink::Surface1,
    Ink::Surface15,
    Ink::Surface2,
    Ink::Surface25,
    Ink::Surface3,
    Ink::Surface4,
    Ink::Surface5,
];

/// The four values of every colour, light then dark then OLED then retro.
///
/// An array rather than a match so the table is the data: a token with a
/// value in one theme and none in another cannot be built here, because
/// the generator resolved the themes as chains before this was written.
const INK_TABLE: &[(Ink, [[u8; 4]; 4])] = &[
    (Ink::BrandGradientBorder, [[0x20, 0x40, 0x20, 0x26], [0x9b, 0xff, 0xa0, 0x14], [0x9b, 0xff, 0xa0, 0x14], [0x9b, 0xff, 0xa0, 0x14]]),
    (Ink::BrandGradientButton, [[0xff, 0xff, 0xff, 0x80], [0xff, 0xff, 0xff, 0x14], [0xff, 0xff, 0xff, 0x14], [0xff, 0xff, 0xff, 0x14]]),
    (Ink::AccentContrast, [[0xff, 0xff, 0xff, 0xff], [0x00, 0x00, 0x00, 0xff], [0x00, 0x00, 0x00, 0xff], [0xff, 0xff, 0xff, 0xff]]),
    (Ink::Ad, [[0x7d, 0x4b, 0xa2, 0x33], [0x7d, 0x4b, 0xa2, 0x33], [0x0d, 0x18, 0x28, 0xff], [0x25, 0x42, 0x1e, 0xff]]),
    (Ink::AdContrast, [[0x00, 0x00, 0x00, 0xff], [0x00, 0x00, 0x00, 0xff], [0x00, 0x00, 0x00, 0xff], [0x00, 0x00, 0x00, 0xff]]),
    (Ink::AdHighlight, [[0x8e, 0x32, 0xf3, 0xff], [0xc7, 0x8a, 0xff, 0xff], [0xc7, 0x8a, 0xff, 0xff], [0x4d, 0x92, 0x27, 0xff]]),
    (Ink::AdRaised, [[0xbe, 0x8c, 0xf3, 0x80], [0xbe, 0x8c, 0xf3, 0x80], [0xbe, 0x8c, 0xf3, 0x80], [0x4d, 0x92, 0x27, 0xff]]),
    (Ink::Base, [[0x2c, 0x2e, 0x31, 0xff], [0xb0, 0xba, 0xc5, 0xff], [0xb0, 0xba, 0xc5, 0xff], [0xc3, 0xc4, 0xb3, 0xff]]),
    (Ink::Bg, [[0xeb, 0xeb, 0xeb, 0xff], [0x16, 0x18, 0x1c, 0xff], [0x00, 0x00, 0x00, 0xff], [0x19, 0x19, 0x17, 0xff]]),
    (Ink::Blue, [[0x1f, 0x68, 0xc0, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x09, 0x9f, 0xef, 0xff]]),
    (Ink::Blue100, [[0xe4, 0xec, 0xfa, 0xff], [0xda, 0xea, 0xff, 0xff], [0xda, 0xea, 0xff, 0xff], [0xda, 0xea, 0xff, 0xff]]),
    (Ink::Blue200, [[0xc3, 0xd9, 0xf4, 0xff], [0xbd, 0xda, 0xff, 0xff], [0xbd, 0xda, 0xff, 0xff], [0xbd, 0xda, 0xff, 0xff]]),
    (Ink::Blue300, [[0x8e, 0xba, 0xeb, 0xff], [0x90, 0xc4, 0xff, 0xff], [0x90, 0xc4, 0xff, 0xff], [0x90, 0xc4, 0xff, 0xff]]),
    (Ink::Blue400, [[0x51, 0x96, 0xdf, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x4f, 0x9c, 0xff, 0xff]]),
    (Ink::Blue50, [[0xf2, 0xf7, 0xfd, 0xff], [0xee, 0xf6, 0xff, 0xff], [0xee, 0xf6, 0xff, 0xff], [0xee, 0xf6, 0xff, 0xff]]),
    (Ink::Blue500, [[0x2b, 0x79, 0xcc, 0xff], [0x35, 0x7f, 0xfc, 0xff], [0x35, 0x7f, 0xfc, 0xff], [0x35, 0x7f, 0xfc, 0xff]]),
    (Ink::Blue600, [[0x1f, 0x68, 0xc0, 0xff], [0x1f, 0x5f, 0xf1, 0xff], [0x1f, 0x5f, 0xf1, 0xff], [0x1f, 0x5f, 0xf1, 0xff]]),
    (Ink::Blue700, [[0x18, 0x4b, 0x8c, 0xff], [0x17, 0x49, 0xde, 0xff], [0x17, 0x49, 0xde, 0xff], [0x17, 0x49, 0xde, 0xff]]),
    (Ink::Blue800, [[0x18, 0x41, 0x74, 0xff], [0x19, 0x3c, 0xb4, 0xff], [0x19, 0x3c, 0xb4, 0xff], [0x19, 0x3c, 0xb4, 0xff]]),
    (Ink::Blue900, [[0x19, 0x38, 0x61, 0xff], [0x1a, 0x37, 0x8e, 0xff], [0x1a, 0x37, 0x8e, 0xff], [0x1a, 0x37, 0x8e, 0xff]]),
    (Ink::Blue950, [[0x11, 0x23, 0x40, 0xff], [0x15, 0x23, 0x56, 0xff], [0x15, 0x23, 0x56, 0xff], [0x15, 0x23, 0x56, 0xff]]),
    (Ink::BlueBg, [[0x1f, 0x68, 0xc0, 0x1a], [0x4f, 0x9c, 0xff, 0x33], [0x4f, 0x9c, 0xff, 0x33], [0x4f, 0x9c, 0xff, 0x33]]),
    (Ink::BlueHighlight, [[0x1f, 0x68, 0xc0, 0x40], [0x4f, 0x9c, 0xff, 0x40], [0x4f, 0x9c, 0xff, 0x40], [0x09, 0x9f, 0xef, 0x40]]),
    (Ink::Brand, [[0x00, 0xaf, 0x5c, 0xff], [0x1b, 0xd9, 0x6a, 0xff], [0x1b, 0xd9, 0x6a, 0xff], [0x4d, 0x92, 0x27, 0xff]]),
    (Ink::ColorBrandHighlight, [[0x00, 0xaf, 0x5c, 0x40], [0x1b, 0xd9, 0x6a, 0x40], [0x1b, 0xd9, 0x6a, 0x40], [0x25, 0x42, 0x1e, 0xff]]),
    (Ink::BrandShadow, [[0x00, 0xaf, 0x5c, 0xb2], [0x1b, 0xd9, 0x6a, 0xb2], [0x1b, 0xd9, 0x6a, 0xb2], [0x1b, 0xd9, 0x6a, 0xb2]]),
    (Ink::ButtonBg, [[0xff, 0xff, 0xff, 0xff], [0x34, 0x36, 0x3c, 0xff], [0x1b, 0x1b, 0x20, 0xff], [0x3a, 0x3b, 0x38, 0xff]]),
    (Ink::ButtonBgSelected, [[0x00, 0xaf, 0x5c, 0xff], [0x1b, 0xd9, 0x6a, 0x40], [0x1b, 0xd9, 0x6a, 0x40], [0x25, 0x42, 0x1e, 0xff]]),
    (Ink::ButtonBorder, [[0xa1, 0xa1, 0xa1, 0x59], [0xc1, 0xbe, 0xd1, 0x1f], [0xc1, 0xbe, 0xd1, 0x1f], [0xc1, 0xbe, 0xd1, 0x1f]]),
    (Ink::ButtonTextSelected, [[0xff, 0xff, 0xff, 0xff], [0x1b, 0xd9, 0x6a, 0xff], [0x1b, 0xd9, 0x6a, 0xff], [0x4d, 0x92, 0x27, 0xff]]),
    (Ink::Contrast, [[0x1a, 0x20, 0x2c, 0xff], [0xff, 0xff, 0xff, 0xff], [0xff, 0xff, 0xff, 0xff], [0xe6, 0xe2, 0xd1, 0xff]]),
    (Ink::Divider, [[0xdd, 0xdd, 0xdd, 0xff], [0x34, 0x36, 0x3c, 0xff], [0x1b, 0x1b, 0x20, 0xff], [0x3a, 0x3b, 0x38, 0xff]]),
    (Ink::DividerDark, [[0xdd, 0xdd, 0xdd, 0xff], [0x64, 0x6c, 0x75, 0xff], [0x64, 0x6c, 0x75, 0xff], [0x64, 0x6c, 0x75, 0xff]]),
    (Ink::FocusRing, [[0xea, 0x80, 0xff, 0xff], [0xea, 0x80, 0xff, 0xff], [0xea, 0x80, 0xff, 0xff], [0xea, 0x80, 0xff, 0xff]]),
    (Ink::Gray, [[0x59, 0x5b, 0x61, 0xff], [0x9f, 0xa4, 0xb3, 0xff], [0x9f, 0xa4, 0xb3, 0xff], [0x71, 0x80, 0x96, 0xff]]),
    (Ink::Gray100, [[0xe5, 0xe5, 0xe8, 0xff], [0xed, 0xef, 0xf2, 0xff], [0xed, 0xef, 0xf2, 0xff], [0xed, 0xef, 0xf2, 0xff]]),
    (Ink::Gray200, [[0xce, 0xcf, 0xd3, 0xff], [0xdf, 0xe2, 0xe6, 0xff], [0xdf, 0xe2, 0xe6, 0xff], [0xdf, 0xe2, 0xe6, 0xff]]),
    (Ink::Gray300, [[0xad, 0xb0, 0xb3, 0xff], [0xca, 0xd0, 0xd7, 0xff], [0xca, 0xd0, 0xd7, 0xff], [0xca, 0xd0, 0xd7, 0xff]]),
    (Ink::Gray400, [[0x83, 0x86, 0x8d, 0xff], [0xb4, 0xba, 0xc5, 0xff], [0xb4, 0xba, 0xc5, 0xff], [0xb4, 0xba, 0xc5, 0xff]]),
    (Ink::Gray50, [[0xf5, 0xf5, 0xf6, 0xff], [0xf5, 0xf7, 0xf8, 0xff], [0xf5, 0xf7, 0xf8, 0xff], [0xf5, 0xf7, 0xf8, 0xff]]),
    (Ink::Gray500, [[0x68, 0x6a, 0x72, 0xff], [0x9f, 0xa4, 0xb3, 0xff], [0x9f, 0xa4, 0xb3, 0xff], [0x9f, 0xa4, 0xb3, 0xff]]),
    (Ink::Gray600, [[0x59, 0x5b, 0x61, 0xff], [0x8a, 0x8d, 0xa1, 0xff], [0x8a, 0x8d, 0xa1, 0xff], [0x8a, 0x8d, 0xa1, 0xff]]),
    (Ink::Gray700, [[0x4c, 0x4e, 0x52, 0xff], [0x77, 0x7b, 0x8b, 0xff], [0x77, 0x7b, 0x8b, 0xff], [0x77, 0x7b, 0x8b, 0xff]]),
    (Ink::Gray800, [[0x43, 0x44, 0x47, 0xff], [0x61, 0x64, 0x72, 0xff], [0x61, 0x64, 0x72, 0xff], [0x61, 0x64, 0x72, 0xff]]),
    (Ink::Gray900, [[0x3b, 0x3b, 0x3e, 0xff], [0x52, 0x55, 0x5d, 0xff], [0x52, 0x55, 0x5d, 0xff], [0x52, 0x55, 0x5d, 0xff]]),
    (Ink::Gray950, [[0x25, 0x26, 0x27, 0xff], [0x30, 0x31, 0x36, 0xff], [0x30, 0x31, 0x36, 0xff], [0x30, 0x31, 0x36, 0xff]]),
    (Ink::GrayHighlight, [[0x59, 0x5b, 0x61, 0x40], [0x9f, 0xa4, 0xb3, 0x40], [0x9f, 0xa4, 0xb3, 0x40], [0x71, 0x80, 0x96, 0x40]]),
    (Ink::Green, [[0x00, 0xaf, 0x5c, 0xff], [0x1b, 0xd9, 0x6a, 0xff], [0x1b, 0xd9, 0x6a, 0xff], [0x3c, 0xdb, 0x36, 0xff]]),
    (Ink::Green100, [[0xd7, 0xff, 0xeb, 0xff], [0xda, 0xfe, 0xe8, 0xff], [0xda, 0xfe, 0xe8, 0xff], [0xda, 0xfe, 0xe8, 0xff]]),
    (Ink::Green200, [[0xb2, 0xff, 0xd9, 0xff], [0xb8, 0xfa, 0xd2, 0xff], [0xb8, 0xfa, 0xd2, 0xff], [0xb8, 0xfa, 0xd2, 0xff]]),
    (Ink::Green300, [[0x76, 0xff, 0xbc, 0xff], [0x81, 0xf4, 0xaf, 0xff], [0x81, 0xf4, 0xaf, 0xff], [0x81, 0xf4, 0xaf, 0xff]]),
    (Ink::Green400, [[0x33, 0xf5, 0x98, 0xff], [0x42, 0xe6, 0x86, 0xff], [0x42, 0xe6, 0x86, 0xff], [0x42, 0xe6, 0x86, 0xff]]),
    (Ink::Green50, [[0xee, 0xff, 0xf6, 0xff], [0xef, 0xfe, 0xf5, 0xff], [0xef, 0xfe, 0xf5, 0xff], [0xef, 0xfe, 0xf5, 0xff]]),
    (Ink::Green500, [[0x09, 0xde, 0x78, 0xff], [0x1b, 0xd9, 0x6a, 0xff], [0x1b, 0xd9, 0x6a, 0xff], [0x1b, 0xd9, 0x6a, 0xff]]),
    (Ink::Green600, [[0x00, 0xaf, 0x5c, 0xff], [0x0f, 0xaa, 0x4f, 0xff], [0x0f, 0xaa, 0x4f, 0xff], [0x0f, 0xaa, 0x4f, 0xff]]),
    (Ink::Green700, [[0x04, 0x91, 0x4f, 0xff], [0x0f, 0x86, 0x42, 0xff], [0x0f, 0x86, 0x42, 0xff], [0x0f, 0x86, 0x42, 0xff]]),
    (Ink::Green800, [[0x0a, 0x71, 0x41, 0xff], [0x12, 0x69, 0x37, 0xff], [0x12, 0x69, 0x37, 0xff], [0x12, 0x69, 0x37, 0xff]]),
    (Ink::Green900, [[0x0a, 0x5d, 0x38, 0xff], [0x11, 0x56, 0x2f, 0xff], [0x11, 0x56, 0x2f, 0xff], [0x11, 0x56, 0x2f, 0xff]]),
    (Ink::Green950, [[0x00, 0x34, 0x1d, 0xff], [0x03, 0x30, 0x18, 0xff], [0x03, 0x30, 0x18, 0xff], [0x03, 0x30, 0x18, 0xff]]),
    (Ink::GreenBg, [[0x00, 0xaf, 0x5c, 0x1a], [0x1b, 0xd9, 0x6a, 0x33], [0x1b, 0xd9, 0x6a, 0x33], [0x1b, 0xd9, 0x6a, 0x33]]),
    (Ink::GreenHighlight, [[0x00, 0xaf, 0x5c, 0x40], [0x1b, 0xd9, 0x6a, 0x40], [0x1b, 0xd9, 0x6a, 0x40], [0x3c, 0xdb, 0x36, 0x40]]),
    (Ink::Link, [[0x1f, 0x68, 0xc0, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x09, 0x9f, 0xef, 0xff]]),
    (Ink::LinkActive, [[0x1f, 0x68, 0xc0, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x09, 0x9f, 0xef, 0xff]]),
    (Ink::LinkHover, [[0x1f, 0x68, 0xc0, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x4f, 0x9c, 0xff, 0xff], [0x09, 0x9f, 0xef, 0xff]]),
    (Ink::Orange, [[0xe0, 0x83, 0x25, 0xff], [0xff, 0xa3, 0x47, 0xff], [0xff, 0xa3, 0x47, 0xff], [0xe8, 0x8d, 0x0d, 0xff]]),
    (Ink::Orange100, [[0xf9, 0xea, 0xcc, 0xff], [0xff, 0xef, 0xd4, 0xff], [0xff, 0xef, 0xd4, 0xff], [0xff, 0xef, 0xd4, 0xff]]),
    (Ink::Orange200, [[0xf2, 0xd4, 0x95, 0xff], [0xff, 0xdb, 0xa8, 0xff], [0xff, 0xdb, 0xa8, 0xff], [0xff, 0xdb, 0xa8, 0xff]]),
    (Ink::Orange300, [[0xec, 0xb8, 0x5d, 0xff], [0xff, 0xc1, 0x71, 0xff], [0xff, 0xc1, 0x71, 0xff], [0xff, 0xc1, 0x71, 0xff]]),
    (Ink::Orange400, [[0xe7, 0xa0, 0x38, 0xff], [0xff, 0xa3, 0x47, 0xff], [0xff, 0xa3, 0x47, 0xff], [0xff, 0xa3, 0x47, 0xff]]),
    (Ink::Orange50, [[0xfd, 0xf8, 0xed, 0xff], [0xff, 0xf8, 0xed, 0xff], [0xff, 0xf8, 0xed, 0xff], [0xff, 0xf8, 0xed, 0xff]]),
    (Ink::Orange500, [[0xe0, 0x83, 0x25, 0xff], [0xfe, 0x7e, 0x11, 0xff], [0xfe, 0x7e, 0x11, 0xff], [0xfe, 0x7e, 0x11, 0xff]]),
    (Ink::Orange600, [[0xc6, 0x60, 0x19, 0xff], [0xef, 0x63, 0x07, 0xff], [0xef, 0x63, 0x07, 0xff], [0xef, 0x63, 0x07, 0xff]]),
    (Ink::Orange700, [[0xa4, 0x44, 0x19, 0xff], [0xc6, 0x48, 0x08, 0xff], [0xc6, 0x48, 0x08, 0xff], [0xc6, 0x48, 0x08, 0xff]]),
    (Ink::Orange800, [[0x86, 0x35, 0x1a, 0xff], [0x9d, 0x3a, 0x0f, 0xff], [0x9d, 0x3a, 0x0f, 0xff], [0x9d, 0x3a, 0x0f, 0xff]]),
    (Ink::Orange900, [[0x6e, 0x2d, 0x19, 0xff], [0x7e, 0x31, 0x10, 0xff], [0x7e, 0x31, 0x10, 0xff], [0x7e, 0x31, 0x10, 0xff]]),
    (Ink::Orange950, [[0x3f, 0x15, 0x09, 0xff], [0x44, 0x16, 0x06, 0xff], [0x44, 0x16, 0x06, 0xff], [0x44, 0x16, 0x06, 0xff]]),
    (Ink::OrangeBg, [[0xe0, 0x83, 0x25, 0x1a], [0xff, 0xa3, 0x47, 0x33], [0xff, 0xa3, 0x47, 0x33], [0xff, 0xa3, 0x47, 0x33]]),
    (Ink::OrangeHighlight, [[0xe0, 0x83, 0x25, 0x40], [0xff, 0xa3, 0x47, 0x40], [0xff, 0xa3, 0x47, 0x40], [0xe8, 0x8d, 0x0d, 0x40]]),
    (Ink::PlatformBtaBabric, [[0x5b, 0xa9, 0x38, 0xff], [0x72, 0xcc, 0x4a, 0xff], [0x72, 0xcc, 0x4a, 0xff], [0x72, 0xcc, 0x4a, 0xff]]),
    (Ink::PlatformBukkit, [[0xe7, 0x83, 0x62, 0xff], [0xf6, 0xaf, 0x7b, 0xff], [0xf6, 0xaf, 0x7b, 0xff], [0xf6, 0xaf, 0x7b, 0xff]]),
    (Ink::PlatformBungeecord, [[0xc6, 0x9e, 0x39, 0xff], [0xd2, 0xc0, 0x80, 0xff], [0xd2, 0xc0, 0x80, 0xff], [0xd2, 0xc0, 0x80, 0xff]]),
    (Ink::PlatformFabric, [[0x8a, 0x7b, 0x71, 0xff], [0xdb, 0xb6, 0x9b, 0xff], [0xdb, 0xb6, 0x9b, 0xff], [0xdb, 0xb6, 0x9b, 0xff]]),
    (Ink::PlatformFolia, [[0x6a, 0xa5, 0x4f, 0xff], [0xa5, 0xe3, 0x88, 0xff], [0xa5, 0xe3, 0x88, 0xff], [0xa5, 0xe3, 0x88, 0xff]]),
    (Ink::PlatformForge, [[0x5b, 0x61, 0x97, 0xff], [0x95, 0x9e, 0xef, 0xff], [0x95, 0x9e, 0xef, 0xff], [0x95, 0x9e, 0xef, 0xff]]),
    (Ink::PlatformLiteloader, [[0x4c, 0x90, 0xde, 0xff], [0x7a, 0xb0, 0xee, 0xff], [0x7a, 0xb0, 0xee, 0xff], [0x7a, 0xb0, 0xee, 0xff]]),
    (Ink::PlatformNeoforge, [[0xdc, 0x89, 0x5c, 0xff], [0xf9, 0x9e, 0x6b, 0xff], [0xf9, 0x9e, 0x6b, 0xff], [0xf9, 0x9e, 0x6b, 0xff]]),
    (Ink::PlatformNilloader, [[0xdd, 0x50, 0x88, 0xff], [0xf4, 0x5e, 0x9a, 0xff], [0xf4, 0x5e, 0x9a, 0xff], [0xf4, 0x5e, 0x9a, 0xff]]),
    (Ink::PlatformOrnithe, [[0x60, 0x97, 0xca, 0xff], [0x87, 0xc7, 0xff, 0xff], [0x87, 0xc7, 0xff, 0xff], [0x87, 0xc7, 0xff, 0xff]]),
    (Ink::PlatformPaper, [[0xe6, 0x7e, 0x7e, 0xff], [0xee, 0xaa, 0xaa, 0xff], [0xee, 0xaa, 0xaa, 0xff], [0xee, 0xaa, 0xaa, 0xff]]),
    (Ink::PlatformPurpur, [[0x77, 0x63, 0xa3, 0xff], [0xc3, 0xab, 0xf7, 0xff], [0xc3, 0xab, 0xf7, 0xff], [0xc3, 0xab, 0xf7, 0xff]]),
    (Ink::PlatformQuilt, [[0x8b, 0x61, 0xb4, 0xff], [0xc7, 0x96, 0xf9, 0xff], [0xc7, 0x96, 0xf9, 0xff], [0xc7, 0x96, 0xf9, 0xff]]),
    (Ink::PlatformSpigot, [[0xcd, 0x7a, 0x21, 0xff], [0xf1, 0xcc, 0x84, 0xff], [0xf1, 0xcc, 0x84, 0xff], [0xf1, 0xcc, 0x84, 0xff]]),
    (Ink::PlatformSponge, [[0xc4, 0x95, 0x28, 0xff], [0xf9, 0xe5, 0x80, 0xff], [0xf9, 0xe5, 0x80, 0xff], [0xf9, 0xe5, 0x80, 0xff]]),
    (Ink::PlatformVelocity, [[0x4b, 0x98, 0xb0, 0xff], [0x83, 0xd5, 0xef, 0xff], [0x83, 0xd5, 0xef, 0xff], [0x83, 0xd5, 0xef, 0xff]]),
    (Ink::PlatformWaterfall, [[0x5f, 0x83, 0xcb, 0xff], [0x78, 0xa4, 0xfb, 0xff], [0x78, 0xa4, 0xfb, 0xff], [0x78, 0xa4, 0xfb, 0xff]]),
    (Ink::Purple, [[0x8e, 0x32, 0xf3, 0xff], [0xc7, 0x8a, 0xff, 0xff], [0xc7, 0x8a, 0xff, 0xff], [0x8b, 0x81, 0xe6, 0xff]]),
    (Ink::Purple100, [[0xf2, 0xe7, 0xff, 0xff], [0xf4, 0xe7, 0xff, 0xff], [0xf4, 0xe7, 0xff, 0xff], [0xf4, 0xe7, 0xff, 0xff]]),
    (Ink::Purple200, [[0xe7, 0xd3, 0xff, 0xff], [0xea, 0xd4, 0xff, 0xff], [0xea, 0xd4, 0xff, 0xff], [0xea, 0xd4, 0xff, 0xff]]),
    (Ink::Purple300, [[0xd4, 0xb1, 0xff, 0xff], [0xda, 0xb2, 0xff, 0xff], [0xda, 0xb2, 0xff, 0xff], [0xda, 0xb2, 0xff, 0xff]]),
    (Ink::Purple400, [[0xba, 0x7e, 0xff, 0xff], [0xc7, 0x8a, 0xff, 0xff], [0xc7, 0x8a, 0xff, 0xff], [0xc7, 0x8a, 0xff, 0xff]]),
    (Ink::Purple50, [[0xfa, 0xf5, 0xff, 0xff], [0xfa, 0xf5, 0xff, 0xff], [0xfa, 0xf5, 0xff, 0xff], [0xfa, 0xf5, 0xff, 0xff]]),
    (Ink::Purple500, [[0x9f, 0x4d, 0xff, 0xff], [0xac, 0x51, 0xfb, 0xff], [0xac, 0x51, 0xfb, 0xff], [0xac, 0x51, 0xfb, 0xff]]),
    (Ink::Purple600, [[0x8e, 0x32, 0xf3, 0xff], [0x97, 0x2e, 0xef, 0xff], [0x97, 0x2e, 0xef, 0xff], [0x97, 0x2e, 0xef, 0xff]]),
    (Ink::Purple700, [[0x76, 0x1a, 0xd6, 0xff], [0x82, 0x1e, 0xd2, 0xff], [0x82, 0x1e, 0xd2, 0xff], [0x82, 0x1e, 0xd2, 0xff]]),
    (Ink::Purple800, [[0x65, 0x1b, 0xae, 0xff], [0x6e, 0x1e, 0xab, 0xff], [0x6e, 0x1e, 0xab, 0xff], [0x6e, 0x1e, 0xab, 0xff]]),
    (Ink::Purple900, [[0x53, 0x17, 0x8c, 0xff], [0x5a, 0x19, 0x8a, 0xff], [0x5a, 0x19, 0x8a, 0xff], [0x5a, 0x19, 0x8a, 0xff]]),
    (Ink::Purple950, [[0x37, 0x03, 0x68, 0xff], [0x3d, 0x05, 0x66, 0xff], [0x3d, 0x05, 0x66, 0xff], [0x3d, 0x05, 0x66, 0xff]]),
    (Ink::PurpleBg, [[0x8e, 0x32, 0xf3, 0x1a], [0xc7, 0x8a, 0xff, 0x33], [0xc7, 0x8a, 0xff, 0x33], [0xc7, 0x8a, 0xff, 0x33]]),
    (Ink::PurpleHighlight, [[0x8e, 0x32, 0xf3, 0x40], [0xc7, 0x8a, 0xff, 0x40], [0xc7, 0x8a, 0xff, 0x40], [0x8b, 0x81, 0xe6, 0x40]]),
    (Ink::RaisedBg, [[0xf8, 0xf8, 0xf8, 0xff], [0x27, 0x29, 0x2e, 0xff], [0x10, 0x10, 0x13, 0xff], [0x23, 0x24, 0x21, 0xff]]),
    (Ink::Red, [[0xcb, 0x22, 0x45, 0xff], [0xff, 0x49, 0x6e, 0xff], [0xff, 0x49, 0x6e, 0xff], [0xe8, 0x20, 0x0d, 0xff]]),
    (Ink::Red100, [[0xfe, 0xe5, 0xe7, 0xff], [0xff, 0xe2, 0xe6, 0xff], [0xff, 0xe2, 0xe6, 0xff], [0xff, 0xe2, 0xe6, 0xff]]),
    (Ink::Red200, [[0xfc, 0xcf, 0xd3, 0xff], [0xff, 0xca, 0xd3, 0xff], [0xff, 0xca, 0xd3, 0xff], [0xff, 0xca, 0xd3, 0xff]]),
    (Ink::Red300, [[0xfa, 0xa7, 0xb1, 0xff], [0xff, 0x9f, 0xae, 0xff], [0xff, 0x9f, 0xae, 0xff], [0xff, 0x9f, 0xae, 0xff]]),
    (Ink::Red400, [[0xf6, 0x76, 0x87, 0xff], [0xff, 0x69, 0x84, 0xff], [0xff, 0x69, 0x84, 0xff], [0xff, 0x69, 0x84, 0xff]]),
    (Ink::Red50, [[0xfe, 0xf2, 0xf2, 0xff], [0xff, 0xf0, 0xf1, 0xff], [0xff, 0xf0, 0xf1, 0xff], [0xff, 0xf0, 0xf1, 0xff]]),
    (Ink::Red500, [[0xed, 0x46, 0x61, 0xff], [0xff, 0x49, 0x6e, 0xff], [0xff, 0x49, 0x6e, 0xff], [0xff, 0x49, 0x6e, 0xff]]),
    (Ink::Red600, [[0xcb, 0x22, 0x45, 0xff], [0xed, 0x11, 0x48, 0xff], [0xed, 0x11, 0x48, 0xff], [0xed, 0x11, 0x48, 0xff]]),
    (Ink::Red700, [[0xb7, 0x19, 0x3d, 0xff], [0xc8, 0x08, 0x3d, 0xff], [0xc8, 0x08, 0x3d, 0xff], [0xc8, 0x08, 0x3d, 0xff]]),
    (Ink::Red800, [[0x9a, 0x17, 0x39, 0xff], [0xa8, 0x09, 0x3a, 0xff], [0xa8, 0x09, 0x3a, 0xff], [0xa8, 0x09, 0x3a, 0xff]]),
    (Ink::Red900, [[0x84, 0x17, 0x38, 0xff], [0x8f, 0x0c, 0x38, 0xff], [0x8f, 0x0c, 0x38, 0xff], [0x8f, 0x0c, 0x38, 0xff]]),
    (Ink::Red950, [[0x49, 0x08, 0x19, 0xff], [0x50, 0x01, 0x1a, 0xff], [0x50, 0x01, 0x1a, 0xff], [0x50, 0x01, 0x1a, 0xff]]),
    (Ink::RedBg, [[0xcb, 0x22, 0x45, 0x1a], [0xff, 0x49, 0x6e, 0x33], [0xff, 0x49, 0x6e, 0x33], [0xff, 0x49, 0x6e, 0x33]]),
    (Ink::RedHighlight, [[0xcb, 0x22, 0x45, 0x40], [0xff, 0x49, 0x6e, 0x40], [0xff, 0x49, 0x6e, 0x40], [0xe8, 0x20, 0x0d, 0x40]]),
    (Ink::Scrollbar, [[0x96, 0xa2, 0xb0, 0xff], [0x42, 0x44, 0x4a, 0xff], [0x25, 0x26, 0x2b, 0xff], [0x5a, 0x5c, 0x58, 0xff]]),
    (Ink::Secondary, [[0x48, 0x4d, 0x54, 0xff], [0x96, 0xa2, 0xb0, 0xff], [0x96, 0xa2, 0xb0, 0xff], [0x9b, 0x9e, 0x98, 0xff]]),
    (Ink::SuperRaisedBg, [[0xff, 0xff, 0xff, 0xff], [0x34, 0x36, 0x3c, 0xff], [0x1b, 0x1b, 0x20, 0xff], [0x3a, 0x3b, 0x38, 0xff]]),
    (Ink::TextDefault, [[0x2c, 0x2e, 0x31, 0xff], [0xb0, 0xba, 0xc5, 0xff], [0xb0, 0xba, 0xc5, 0xff], [0xc3, 0xc4, 0xb3, 0xff]]),
    (Ink::TextPrimary, [[0x1a, 0x20, 0x2c, 0xff], [0xff, 0xff, 0xff, 0xff], [0xff, 0xff, 0xff, 0xff], [0xe6, 0xe2, 0xd1, 0xff]]),
    (Ink::TextTertiary, [[0x48, 0x4d, 0x54, 0xff], [0x96, 0xa2, 0xb0, 0xff], [0x96, 0xa2, 0xb0, 0xff], [0x9b, 0x9e, 0x98, 0xff]]),
    (Ink::TooltipBg, [[0xf8, 0xf8, 0xf8, 0xff], [0x27, 0x29, 0x2e, 0xff], [0x10, 0x10, 0x13, 0xff], [0x23, 0x24, 0x21, 0xff]]),
    (Ink::TooltipText, [[0x1a, 0x20, 0x2c, 0xff], [0xff, 0xff, 0xff, 0xff], [0xff, 0xff, 0xff, 0xff], [0xe6, 0xe2, 0xd1, 0xff]]),
    (Ink::DarkColorBase, [[0xb0, 0xba, 0xc5, 0xff], [0xb0, 0xba, 0xc5, 0xff], [0xb0, 0xba, 0xc5, 0xff], [0xb0, 0xba, 0xc5, 0xff]]),
    (Ink::DarkColorContrast, [[0xec, 0xf9, 0xfb, 0xff], [0xec, 0xf9, 0xfb, 0xff], [0xec, 0xf9, 0xfb, 0xff], [0xec, 0xf9, 0xfb, 0xff]]),
    (Ink::SplashOverlay, [[0xb5, 0xff, 0xd5, 0x50], [0x16, 0x18, 0x1c, 0xa3], [0x16, 0x18, 0x1c, 0xa3], [0x16, 0x18, 0x1c, 0xa3]]),
    (Ink::SplashTintBottom, [[0xb7, 0xe2, 0xff, 0x90], [0x11, 0x23, 0x2b, 0x80], [0x11, 0x23, 0x2b, 0x80], [0x11, 0x23, 0x2b, 0x80]]),
    (Ink::SplashTintTop, [[0xb9, 0xff, 0xcf, 0x77], [0x42, 0x83, 0x5c, 0x46], [0x42, 0x83, 0x5c, 0x46], [0x42, 0x83, 0x5c, 0x46]]),
    (Ink::Surface1, [[0xeb, 0xeb, 0xeb, 0xff], [0x16, 0x18, 0x1c, 0xff], [0x00, 0x00, 0x00, 0xff], [0x19, 0x19, 0x17, 0xff]]),
    (Ink::Surface15, [[0xed, 0xed, 0xed, 0xff], [0x1a, 0x1c, 0x20, 0xff], [0x05, 0x05, 0x06, 0xff], [0x1a, 0x1c, 0x20, 0xff]]),
    (Ink::Surface2, [[0xf5, 0xf5, 0xf5, 0xff], [0x1d, 0x1f, 0x23, 0xff], [0x09, 0x09, 0x0a, 0xff], [0x16, 0x16, 0x15, 0xff]]),
    (Ink::Surface25, [[0xee, 0xf1, 0xf5, 0xff], [0x22, 0x24, 0x29, 0xff], [0x0c, 0x0d, 0x11, 0xff], [0x3a, 0x3c, 0x3e, 0xff]]),
    (Ink::Surface3, [[0xf8, 0xf8, 0xf8, 0xff], [0x27, 0x29, 0x2e, 0xff], [0x10, 0x10, 0x13, 0xff], [0x23, 0x24, 0x21, 0xff]]),
    (Ink::Surface4, [[0xff, 0xff, 0xff, 0xff], [0x34, 0x36, 0x3c, 0xff], [0x1b, 0x1b, 0x20, 0xff], [0x3a, 0x3b, 0x38, 0xff]]),
    (Ink::Surface5, [[0xdd, 0xdd, 0xdd, 0xff], [0x42, 0x44, 0x4a, 0xff], [0x25, 0x26, 0x2b, 0xff], [0x5a, 0x5c, 0x58, 0xff]]),
];

/// A length the reference names, e.g. `Span::RadiusMd` for `--radius-md`.
///
/// Stored in logical pixels, converted from the `rem` the reference writes
/// against a root of 16px, which is the browser default it relies on.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Span {
    /// `--gap-lg`
    GapLg,
    /// `--gap-md`
    GapMd,
    /// `--gap-sm`
    GapSm,
    /// `--gap-xl`
    GapXl,
    /// `--gap-xs`
    GapXs,
    /// `--radius-lg`
    RadiusLg,
    /// `--radius-max`
    RadiusMax,
    /// `--radius-md`
    RadiusMd,
    /// `--radius-sm`
    RadiusSm,
    /// `--radius-xl`
    RadiusXl,
    /// `--radius-xs`
    RadiusXs,
}

const SPAN_TABLE: &[(Span, f32)] = &[
    (Span::GapLg, 16.0),
    (Span::GapMd, 12.0),
    (Span::GapSm, 8.0),
    (Span::GapXl, 24.0),
    (Span::GapXs, 4.0),
    (Span::RadiusLg, 16.0),
    (Span::RadiusMax, 999999999.0),
    (Span::RadiusMd, 12.0),
    (Span::RadiusSm, 8.0),
    (Span::RadiusXl, 20.0),
    (Span::RadiusXs, 4.0),
];

/// Every length token, in the order the table below is sorted in.
pub const ALL_SPAN: &[Span] = &[
    Span::GapLg,
    Span::GapMd,
    Span::GapSm,
    Span::GapXl,
    Span::GapXs,
    Span::RadiusLg,
    Span::RadiusMax,
    Span::RadiusMd,
    Span::RadiusSm,
    Span::RadiusXl,
    Span::RadiusXs,
];

/// A bare number the reference names, e.g. `Factor::HoverBrightness`.
///
/// These are the factors that are not colours and not lengths: the hover
/// brightness (`1.25` in dark, `0.9` in light -- the two directions a
/// control moves under the pointer) and the splash's own opacities.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Factor {
    /// `--hover-brightness`
    HoverBrightness,
    /// `--splash-cube-opacity`
    SplashCubeOpacity,
}

/// The four values of every bare number, in the same order as [`Theme`].
const FACTOR_TABLE: &[(Factor, [f32; 4])] = &[
    (Factor::HoverBrightness, [0.9, 1.25, 1.25, 1.25]),
    (Factor::SplashCubeOpacity, [0.4, 0.8, 0.8, 0.8]),
];

/// Every bare-number token, in the order the table below is sorted in.
pub const ALL_FACTOR: &[Factor] = &[
    Factor::HoverBrightness,
    Factor::SplashCubeOpacity,
];

/// A cubic-bezier the reference uses, by name where it has one.
///
/// `Curve::EaseOutExpo` is the reference's own `--ease-out-expo`; the CSS
/// specification's named easings (`ease`, `ease-in-out`, ...) are here too
/// because the reference's transitions name them rather than spelling
/// their four numbers out.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Curve {
    Ease,
    EaseInOut,
    EaseOut,
    EaseOutExpo,
    Linear,
}

/// `(x1, y1, x2, y2)` of every curve, in the order the enum declares them.
const CURVE_TABLE: &[(Curve, [f32; 4])] = &[
    (Curve::Ease, [0.25, 0.1, 0.25, 1.0]),
    (Curve::EaseInOut, [0.42, 0.0, 0.58, 1.0]),
    (Curve::EaseOut, [0.0, 0.0, 0.58, 1.0]),
    (Curve::EaseOutExpo, [0.16, 1.0, 0.3, 1.0]),
    (Curve::Linear, [0.0, 0.0, 1.0, 1.0]),
];

/// Every curve, in the order the table below is sorted in.
pub const ALL_CURVE: &[Curve] = &[
    Curve::Ease,
    Curve::EaseInOut,
    Curve::EaseOut,
    Curve::EaseOutExpo,
    Curve::Linear,
];

/// A value the reference states that is not a scalar: a gradient, a
/// shadow, a blend mode, a font. Kept verbatim so the shell can read what
/// it has to draw and a porter can see the reference's own wording.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Raw {
    /// `--brand-gradient-bg`
    BrandGradientBg,
    /// `--brand-gradient-fade-out-color`
    BrandGradientFadeOutColor,
    /// `--brand-gradient-strong-bg`
    BrandGradientStrongBg,
    /// `--color-gradient-button-bg`
    GradientButtonBg,
    /// `--loading-bar-gradient`
    LoadingBarGradient,
    /// `--shadow-button`
    ShadowButton,
    /// `--shadow-card`
    ShadowCard,
    /// `--shadow-floating`
    ShadowFloating,
    /// `--shadow-inset`
    ShadowInset,
    /// `--shadow-inset-lg`
    ShadowInsetLg,
    /// `--shadow-inset-sm`
    ShadowInsetSm,
    /// `--shadow-raised`
    ShadowRaised,
    /// `--shadow-raised-lg`
    ShadowRaisedLg,
    /// `--splash-cube-blend`
    SplashCubeBlend,
}

/// The four values of every raw token. An empty string means the token is
/// not declared in that theme, and the next theme along does not supply it
/// either -- which is a fact about the reference, not a gap here.
const RAW_TABLE: &[(Raw, [&str; 4])] = &[
    (Raw::BrandGradientBg, ["linear-gradient( 0deg, rgba(68, 182, 138, 0.175) 0%, rgba(58, 250, 112, 0.125) 100% )", "linear-gradient(0deg, rgba(14, 35, 19, 0.2) 0%, rgba(55, 137, 73, 0.1) 100%)", "linear-gradient( 0deg, rgba(22, 66, 51, 0.15) 0%, rgba(55, 137, 73, 0.1) 100% )", "linear-gradient(0deg, rgba(14, 35, 19, 0.2) 0%, rgba(55, 137, 73, 0.1) 100%)"]),
    (Raw::BrandGradientFadeOutColor, ["linear-gradient(to bottom, rgba(213, 235, 224, 0), #d0ece0 70%)", "linear-gradient(to bottom, rgba(24, 30, 31, 0), #171d1e 80%)", "linear-gradient(to bottom, rgba(24, 30, 31, 0), #171d1e 80%)", "linear-gradient(to bottom, rgba(24, 30, 31, 0), #171d1e 80%)"]),
    (Raw::BrandGradientStrongBg, ["linear-gradient( 270deg, rgba(68, 182, 138, 0.175) 0%, rgba(36, 225, 91, 0.12) 100% )", "linear-gradient(270deg, #09110d 10%, #131f17 100%)", "linear-gradient( 270deg, rgba(9, 18, 14, 0.6) 10%, rgba(19, 31, 23, 0.5) 100% )", "#3a3b38"]),
    (Raw::GradientButtonBg, ["linear-gradient(180deg, #f8f9fa 0%, #dce0e6 100%)", "linear-gradient(180deg, #3a3d47 0%, #33363d 100%)", "linear-gradient(180deg, #1b1b20 0%, #25262b 100%)", "linear-gradient(180deg, #3a3d47 0%, #33363d 100%)"]),
    (Raw::LoadingBarGradient, ["linear-gradient(to right, var(--color-brand) 0%, #00af5c 100%)", "linear-gradient(to right, var(--color-brand) 0%, #1ffa9a 100%)", "linear-gradient(to right, var(--color-brand) 0%, #1ffa9a 100%)", "linear-gradient(to right, var(--color-brand) 0%, #1ffa9a 100%)"]),
    (Raw::ShadowButton, ["0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.15)", "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.15)", "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.15)", "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.15)"]),
    (Raw::ShadowCard, ["rgba(50, 50, 100, 0.1) 0px 2px 4px 0px", "rgba(0, 0, 0, 0.25) 0px 2px 4px 0px", "rgba(0, 0, 0, 0.25) 0px 2px 4px 0px", "rgba(0, 0, 0, 0.25) 0px 2px 4px 0px"]),
    (Raw::ShadowFloating, ["hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0.1) 0px 4px 6px -1px, hsla(0, 0%, 0%, 0.1) 0px 2px 4px -1px", "hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0.1) 0px 4px 6px -1px, rgba(0, 0, 0, 0.06) 0px 2px 4px -1px", "hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0.1) 0px 4px 6px -1px, rgba(0, 0, 0, 0.06) 0px 2px 4px -1px", "hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0) 0px 0px 0px 0px, hsla(0, 0%, 0%, 0.1) 0px 4px 6px -1px, rgba(0, 0, 0, 0.06) 0px 2px 4px -1px"]),
    (Raw::ShadowInset, ["inset 0px -2px 2px hsla(221, 39%, 91%, 0.05)", "inset 0px -2px 2px hsla(221, 39%, 11%, 0.05)", "inset 0px -2px 2px hsla(221, 39%, 11%, 0.05)", "inset 0px -2px 2px hsla(221, 39%, 11%, 0.05)"]),
    (Raw::ShadowInsetLg, ["inset 0px -2px 2px hsla(221, 39%, 91%, 0.1)", "inset 0px -2px 2px hsla(221, 39%, 11%, 0.1)", "inset 0px -2px 2px hsla(221, 39%, 11%, 0.1)", "inset 0px -2px 2px hsla(221, 39%, 11%, 0.1)"]),
    (Raw::ShadowInsetSm, ["inset 0px -1px 2px hsla(221, 39%, 91%, 0.15)", "inset 0px -1px 1px hsla(221, 39%, 11%, 0.25)", "inset 0px -1px 1px hsla(221, 39%, 11%, 0.25)", "inset 0px -1px 1px hsla(221, 39%, 11%, 0.25)"]),
    (Raw::ShadowRaised, ["0.3px 0.5px 0.6px hsl(var(--shadow-color) / 0.15), 1px 2px 2.2px -1.7px hsl(var(--shadow-color) / 0.12), 4.4px 8.8px 9.7px -3.4px hsl(var(--shadow-color) / 0.09)", "0px -2px 4px hsla(221, 39%, 11%, 0.1)", "0px -2px 4px hsla(221, 39%, 11%, 0.1)", "0px -2px 4px hsla(221, 39%, 11%, 0.1)"]),
    (Raw::ShadowRaisedLg, ["0px 2px 4px hsla(221, 39%, 11%, 0.2)", "0px 2px 4px hsla(221, 39%, 11%, 0.2)", "0px 2px 4px hsla(221, 39%, 11%, 0.2)", "0px 2px 4px hsla(221, 39%, 11%, 0.2)"]),
    (Raw::SplashCubeBlend, ["multiply", "normal", "normal", "normal"]),
];

/// Every raw token, in the order the table below is sorted in.
pub const ALL_RAW: &[Raw] = &[
    Raw::BrandGradientBg,
    Raw::BrandGradientFadeOutColor,
    Raw::BrandGradientStrongBg,
    Raw::GradientButtonBg,
    Raw::LoadingBarGradient,
    Raw::ShadowButton,
    Raw::ShadowCard,
    Raw::ShadowFloating,
    Raw::ShadowInset,
    Raw::ShadowInsetLg,
    Raw::ShadowInsetSm,
    Raw::ShadowRaised,
    Raw::ShadowRaisedLg,
    Raw::SplashCubeBlend,
];

/// The Tailwind scale the reference's markup is written in.
///
/// Its own `tailwind.config.ts` sets `presets: [preset]`, and the preset
/// only renames colours -- every entry in it is `var(--...)`. So the scale
/// underneath is Tailwind's default theme, which is what these are, in
/// logical pixels against the same root the lengths above assume.
pub struct Tailwind {
    /// `p-4`, `gap-2`, `w-12` — the 4px-based spacing scale.
    pub spacing: &'static [f32],
    /// `rounded-lg` and friends, in the order Tailwind names them.
    pub radius: &'static [f32],
    /// `text-sm`, `text-3xl` — font size, then the line height beside it.
    pub font_size: &'static [(f32, f32)],
    /// `font-normal` through `font-black`.
    pub font_weight: &'static [(u16, u16)],
    /// `duration-75` through `duration-1000`, in milliseconds.
    pub duration_ms: &'static [u32],
}

/// The default theme, as the reference inherits it.
pub const TAILWIND: Tailwind = Tailwind {
    spacing: &[
        0.0,
        1.0,
        2.0,
        4.0,
        6.0,
        8.0,
        10.0,
        12.0,
        14.0,
        16.0,
        20.0,
        24.0,
        28.0,
        32.0,
        36.0,
        40.0,
        44.0,
        48.0,
        56.0,
        64.0,
        80.0,
        96.0,
        112.0,
        128.0,
        144.0,
        160.0,
        176.0,
        192.0,
        208.0,
        224.0,
        240.0,
        256.0,
        288.0,
        320.0,
        384.0,
    ],
    radius: &[
        0.0, // rounded-none
        2.0, // rounded-sm
        4.0, // rounded-DEFAULT
        6.0, // rounded-md
        8.0, // rounded-lg
        12.0, // rounded-xl
        16.0, // rounded-2xl
        24.0, // rounded-3xl
        159984.0, // rounded-full
    ],
    font_size: &[
        (12.0, 16.0), // text-xs
        (14.0, 20.0), // text-sm
        (16.0, 24.0), // text-base
        (18.0, 28.0), // text-lg
        (20.0, 28.0), // text-xl
        (24.0, 32.0), // text-2xl
        (30.0, 36.0), // text-3xl
        (36.0, 40.0), // text-4xl
        (48.0, 16.0), // text-5xl
        (60.0, 16.0), // text-6xl
        (72.0, 16.0), // text-7xl
        (96.0, 16.0), // text-8xl
        (128.0, 16.0), // text-9xl
    ],
    font_weight: &[
        (100, 100), // font-thin
        (200, 200), // font-extralight
        (300, 300), // font-light
        (400, 400), // font-normal
        (500, 500), // font-medium
        (600, 600), // font-semibold
        (700, 700), // font-bold
        (800, 800), // font-extrabold
        (900, 900), // font-black
    ],
    duration_ms: &[
        0,
        75,
        100,
        150,
        200,
        300,
        500,
        700,
        1000,
    ],
};

/// The colour a token is in a theme.
///
/// Total by construction: every token is resolved for every theme before
/// this file is written, so there is no `Option` to handle at a call site
/// and no `unwrap` to justify. A token missing from a theme is a
/// generation error, printed by `tools/gen_theme.py --report`.
pub fn ink(theme: Theme, token: Ink) -> Color {
    let [r, g, b, a] = ink_rgba(theme, token);
    Color::from_rgba8(r, g, b, a as f32 / 255.0)
}

/// The same value as `ink`, as the four bytes the CSS declared.
///
/// Separate from `ink` so that a gate can assert a hex value without
/// going through a float, and so that the rounding a float colour
/// introduces never decides whether a gate passes.
pub fn ink_rgba(theme: Theme, token: Ink) -> [u8; 4] {
    match INK_TABLE.binary_search_by_key(&(token as u8), |(key, _)| *key as u8) {
        Ok(found) => INK_TABLE[found].1[theme.index()],
        // Unreachable by construction, and a value rather than a panic
        // because this crate denies `unwrap` outside tests. Transparent
        // black is the one answer that cannot be mistaken for paint.
        Err(_) => [0, 0, 0, 0],
    }
}

/// A length, in logical pixels.
pub fn span(token: Span) -> f32 {
    match SPAN_TABLE.binary_search_by_key(&(token as u8), |(key, _)| *key as u8) {
        Ok(found) => SPAN_TABLE[found].1,
        Err(_) => 0.0,
    }
}

/// A bare number, per theme.
pub fn factor(theme: Theme, token: Factor) -> f32 {
    match FACTOR_TABLE.binary_search_by_key(&(token as u8), |(key, _)| *key as u8) {
        Ok(found) => FACTOR_TABLE[found].1[theme.index()],
        Err(_) => 0.0,
    }
}

/// The four control points of a curve, for a tween to evaluate.
pub fn curve(token: Curve) -> [f32; 4] {
    match CURVE_TABLE.binary_search_by_key(&(token as u8), |(key, _)| *key as u8) {
        Ok(found) => CURVE_TABLE[found].1,
        Err(_) => [0.0, 0.0, 1.0, 1.0],
    }
}

/// A value that is not a scalar, per theme, verbatim.
pub fn raw(theme: Theme, token: Raw) -> &'static str {
    match RAW_TABLE.binary_search_by_key(&(token as u8), |(key, _)| *key as u8) {
        Ok(found) => RAW_TABLE[found].1[theme.index()],
        Err(_) => "",
    }
}

/// One transition the reference declares: what moves, how long it takes,
/// and on which curve.
pub struct Motion {
    /// The CSS property that moves, as the reference names it.
    pub property: &'static str,
    /// How long it takes, in milliseconds.
    pub millis: u32,
    /// The curve it moves on.
    pub curve: Curve,
    /// Where in the reference it was read, so a port can go and look.
    pub source: &'static str,
}

/// Every transition the reference declares with one property and one
/// duration, deduplicated. The shell's tween engine takes its numbers from
/// here rather than choosing them, which is what NOTES 29 asks for.
pub const MOTION: &[Motion] = &[
    Motion { property: "all", millis: 200, curve: Curve::EaseOut, source: "ui/src/components/modal/NewModal.vue" },
    Motion { property: "all", millis: 200, curve: Curve::Ease, source: "ui/src/layouts/shared/files-tab/components/FileNavbar.vue" },
    Motion { property: "all", millis: 200, curve: Curve::EaseInOut, source: "ui/src/components/modal/NewModal.vue" },
    Motion { property: "all", millis: 250, curve: Curve::Ease, source: "ui/src/layouts/shared/files-tab/components/upload/FileUploadDropdown.vue" },
    Motion { property: "all", millis: 250, curve: Curve::EaseInOut, source: "ui/src/components/nav/NotificationPanel.vue" },
    Motion { property: "all", millis: 300, curve: Curve::EaseOut, source: "ui/src/components/modal/OpenInAppModal.vue" },
    Motion { property: "all", millis: 300, curve: Curve::Ease, source: "ui/src/components/chart/Chart.vue" },
    Motion { property: "all", millis: 300, curve: Curve::EaseInOut, source: "ui/src/components/nav/PopupNotificationPanel.vue" },
    Motion { property: "all", millis: 500, curve: Curve::EaseOut, source: "ui/src/layouts/wrapped/hosting/manage/backups.vue" },
    Motion { property: "background-color", millis: 200, curve: Curve::EaseInOut, source: "app-frontend/src/pages/project/Index.vue" },
    Motion { property: "bottom", millis: 250, curve: Curve::EaseInOut, source: "ui/src/components/base/FloatingActionBar.vue" },
    Motion { property: "box-shadow", millis: 100, curve: Curve::EaseInOut, source: "app-frontend/src/assets/stylesheets/global.scss" },
    Motion { property: "clip-path", millis: 250, curve: Curve::EaseOutExpo, source: "ui/src/components/base/Slider.vue" },
    Motion { property: "filter", millis: 100, curve: Curve::EaseInOut, source: "ui/src/components/base/DropdownSelect.vue" },
    Motion { property: "filter", millis: 200, curve: Curve::EaseInOut, source: "ui/src/components/base/DropdownSelect.vue" },
    Motion { property: "height", millis: 200, curve: Curve::Ease, source: "ui/src/layouts/shared/files-tab/components/upload/FileUploadDropdown.vue" },
    Motion { property: "height", millis: 220, curve: Curve::EaseInOut, source: "ui/src/components/servers/access/AuditLogTable.vue" },
    Motion { property: "opacity", millis: 125, curve: Curve::EaseOut, source: "ui/src/components/base/SmartClickable.vue" },
    Motion { property: "opacity", millis: 200, curve: Curve::EaseInOut, source: "app-frontend/src/assets/stylesheets/global.scss" },
    Motion { property: "opacity", millis: 250, curve: Curve::EaseInOut, source: "ui/src/components/base/BaseTerminal.vue" },
    Motion { property: "opacity", millis: 300, curve: Curve::EaseOut, source: "ui/src/components/modal/OpenInAppModal.vue" },
    Motion { property: "opacity", millis: 300, curve: Curve::Ease, source: "ui/src/components/base/AppearingProgressBar.vue" },
    Motion { property: "opacity", millis: 300, curve: Curve::EaseInOut, source: "app-frontend/src/components/ui/SplashScreen.vue" },
    Motion { property: "opacity", millis: 350, curve: Curve::EaseInOut, source: "app-frontend/src/components/ui/screenshots-page/card.vue" },
    Motion { property: "outline-color", millis: 150, curve: Curve::Ease, source: "app-frontend/src/components/ui/instance_settings/icon-editor-modal/index.vue" },
    Motion { property: "right", millis: 250, curve: Curve::EaseInOut, source: "ui/src/components/nav/NotificationPanel.vue" },
    Motion { property: "scale", millis: 125, curve: Curve::EaseOut, source: "ui/src/components/base/SmartClickable.vue" },
    Motion { property: "stroke-dashoffset", millis: 50, curve: Curve::Linear, source: "ui/src/components/modal/OpenInAppModal.vue" },
    Motion { property: "transform", millis: 62, curve: Curve::Ease, source: "assets/styles/classes.scss" },
    Motion { property: "transform", millis: 125, curve: Curve::EaseInOut, source: "assets/styles/classes.scss" },
    Motion { property: "transform", millis: 200, curve: Curve::Ease, source: "ui/src/components/base/DropdownSelect.vue" },
    Motion { property: "transform", millis: 200, curve: Curve::EaseInOut, source: "ui/src/layouts/wrapped/hosting/manage/backups.vue" },
    Motion { property: "transform", millis: 300, curve: Curve::EaseInOut, source: "assets/styles/classes.scss" },
    Motion { property: "transform", millis: 2000, curve: Curve::EaseInOut, source: "ui/src/components/brand/TextLogo.vue" },
    Motion { property: "width", millis: 200, curve: Curve::EaseInOut, source: "ui/src/components/base/ProgressBar.vue" },
    Motion { property: "width", millis: 250, curve: Curve::EaseOutExpo, source: "ui/src/components/base/Slider.vue" },
    Motion { property: "width", millis: 300, curve: Curve::EaseOut, source: "app-frontend/src/components/ui/ProgressBar.vue" },
];

/// Transitions the reference writes as a shorthand this tool will not
/// guess at: one duration shared by a comma-separated property list.
///
/// CSS reads `transition: color, background-color 125ms ease-in-out` as
/// *two* transitions with different timings, and splitting it by hand in a
/// generator is how a wrong number gets a plausible name. The reference's
/// own wording is kept instead.
pub const MOTION_VERBATIM: &[(&str, &str)] = &[
    ("app-frontend/src/App.vue", "0.25s ease-in-out"),
    ("app-frontend/src/App.vue", "all 0.5s cubic-bezier(0.15, 1.4, 0.64, 0.96)"),
    ("app-frontend/src/components/ui/NavButton.vue", "opacity 0.25s var(--ease-out-expo), scale 0.25s var(--ease-out-expo)"),
    ("app-frontend/src/components/ui/QuickInstanceSwitcher.vue", "none"),
    ("app-frontend/src/components/ui/QuickInstanceSwitcher.vue", "opacity 0.25s ease, height 0.25s ease"),
    ("app-frontend/src/components/ui/QuickInstanceSwitcher.vue", "opacity 0.25s ease, transform 0.25s ease, height 0.25s ease, margin-top 0.25s ease"),
    ("app-frontend/src/components/ui/SurveyPopup.vue", "opacity 0.25s ease, transform 0.25s cubic-bezier(0.51, 1.08, 0.35, 1.15)"),
    ("app-frontend/src/components/ui/SurveyPopup.vue", "opacity 0.25s ease, transform 0.25s cubic-bezier(0.68, -0.17, 0.23, 0.11)"),
    ("app-frontend/src/components/ui/download-manager/download-manager-bar.vue", "none"),
    ("app-frontend/src/components/ui/download-manager/download-manager-bar.vue", "opacity 160ms ease-out, border-color 150ms cubic-bezier(0.4, 0, 0.2, 1)"),
    ("app-frontend/src/components/ui/download-manager/download-manager-bar.vue", "transform 160ms ease-out, opacity 160ms ease-out"),
    ("app-frontend/src/components/ui/world/RecentWorldsList.vue", "none"),
    ("app-frontend/src/components/ui/world/RecentWorldsList.vue", "opacity 0.25s ease, transform 0.25s ease, height 0.25s ease"),
    ("app-frontend/src/pages/instance/components/settings-modal/settings-options-transition.vue", "grid-template-rows 0.25s var(--ease-out-expo), opacity 0.2s ease-out"),
    ("app-frontend/src/pages/instance/components/settings-modal/settings-options-transition.vue", "none"),
    ("assets/styles/classes.scss", "background-color 0.2s ease-in-out, border-color 0.2s ease-in-out, color 0.2s ease-in-out"),
    ("assets/styles/classes.scss", "content-visibility 0.3s allow-discrete"),
    ("assets/styles/classes.scss", "grid-template-rows 0.3s var(--ease-out-expo)"),
    ("assets/styles/classes.scss", "none"),
    ("assets/styles/classes.scss", "opacity 0.08s ease-out, scale 0.08s ease-out"),
    ("assets/styles/classes.scss", "opacity 0.1s ease-out, scale 0.1s ease-out 50ms"),
    ("assets/styles/classes.scss", "opacity 0.5s ease-in-out, filter 0.2s ease-in-out, scale 0.05s ease-in-out, outline 0.2s ease-in-out"),
    ("assets/styles/classes.scss", "opacity 0.5s ease-in-out, filter 0.2s ease-in-out, transform 0.05s ease-in-out, outline 0.2s ease-in-out"),
    ("assets/styles/classes.scss", "transform 0.125s ease-in-out, opacity 0.125s ease-in-out"),
    ("assets/styles/defaults.scss", "opacity 0.5s ease-in-out, filter 0.2s ease-in-out, transform 0.05s ease-in-out, outline 0.2s ease-in-out"),
    ("ui/src/components/base/Accordion.vue", "grid-template-rows 0.3s ease-in-out"),
    ("ui/src/components/base/Accordion.vue", "none"),
    ("ui/src/components/base/Collapsible.vue", "grid-template-rows 0.3s ease-in-out"),
    ("ui/src/components/base/Collapsible.vue", "none"),
    ("ui/src/components/base/CollapsibleAdmonition.vue", "opacity 300ms ease-in-out, transform 300ms ease-in-out"),
    ("ui/src/components/base/CollapsibleRegion.vue", "grid-template-rows 500ms var(--ease-out-expo)"),
    ("ui/src/components/base/CollapsibleRegion.vue", "none"),
    ("ui/src/components/base/DropArea.vue", "none"),
    ("ui/src/components/base/DropArea.vue", "visibility 0.2s ease-in-out, background-color 0.1s ease-in-out"),
    ("ui/src/components/base/DropdownSelect.vue", "0.05s"),
    ("ui/src/components/base/FloatingActionBar.vue", "transform 0.25s cubic-bezier(0.15, 1.4, 0.64, 0.96), opacity 0.25s cubic-bezier(0.15, 1.4, 0.64, 0.96)"),
    ("ui/src/components/base/FloatingActionBar.vue", "transform 0.25s ease, opacity 0.25s ease"),
    ("ui/src/components/base/LoadingBar.vue", "'width 0.1s ease-in-out, height 0.1s ease-out, opacity 0.4s',"),
    ("ui/src/components/base/MarkdownEditorImpl.vue", "opacity 0.5s ease-in-out, filter 0.2s ease-in-out, scale 0.05s ease-in-out, outline 0.2s ease-in-out"),
    ("ui/src/components/base/NavTabs.vue", "color 100ms cubic-bezier(0.4, 0, 0.2, 1)"),
    ("ui/src/components/base/NavTabs.vue", "left 80ms cubic-bezier(0.4, 0, 0.2, 1) v-bind(leftDelay), right 80ms cubic-bezier(0.4, 0, 0.2, 1) v-bind(rightDelay), top 80ms cubic-bezier(0.4, 0, 0.2, 1) v-bind(topDelay), bottom 80ms cubic-bezier(0.4, 0, 0.2, 1) v-bind(bottomDelay)"),
    ("ui/src/components/base/OptionGroup.vue", "all 150ms cubic-bezier(0.4, 0, 0.2, 1), opacity 250ms cubic-bezier(0.5, 0, 0.2, 1) 50ms"),
    ("ui/src/components/base/ProgressSpinner.vue", "--_progress 0.125s ease-in-out"),
    ("ui/src/components/base/ReadyTransition.vue", "opacity v-bind('`${props.duration"),
    ("ui/src/components/base/ScrollablePanel.vue", "--_top-fade-height 0.05s linear, --_bottom-fade-height 0.05s linear"),
    ("ui/src/components/base/Slider.vue", "none"),
    ("ui/src/components/base/StackedAdmonitions.vue", "exitTransition"),
    ("ui/src/components/base/StackedAdmonitions.vue", "shellExitTransition,"),
    ("ui/src/components/base/ToggleCard.vue", "grid-template-rows 0.25s var(--ease-out-expo)"),
    ("ui/src/components/floating/Tooltip.vue", "left 0.15s var(--ease-out-expo), top 0.15s var(--ease-out-expo)"),
    ("ui/src/components/modal/NewModal.vue", "none"),
    ("ui/src/components/nav/PopupNotificationPanel.vue", "opacity 0.2s ease-in-out, transform 0.2s ease-in-out"),
    ("ui/src/components/nav/PopupNotificationPanel.vue", "opacity 0.3s ease-in-out, transform 0.3s ease-in-out"),
    ("ui/src/components/search/SearchFilterGroup.vue", "grid-template-rows 0.2s ease-in-out"),
    ("ui/src/components/search/SearchFilterGroup.vue", "none"),
    ("ui/src/components/servers/access/AuditLogTable.vue", "opacity 180ms ease-in-out, transform 180ms ease-in-out"),
    ("ui/src/components/user/AccountSwitchOverlay.vue", "0.25s ease-in-out"),
    ("ui/src/layouts/shared/files-tab/components/editor/EditorFindReplace.vue", "opacity 0.15s ease, transform 0.15s ease"),
    ("ui/src/layouts/shared/files-tab/layout.vue", "opacity 300ms ease-in-out, transform 300ms ease-in-out"),
    ("ui/src/layouts/wrapped/hosting/manage/backups.vue", "opacity 300ms ease-in-out, transform 300ms ease-in-out"),
    ("ui/src/layouts/wrapped/hosting/manage/index.vue", "opacity 300ms ease-in-out, transform 300ms ease-in-out"),
    ("ui/src/styles/tailwind-utilities.css", "color, background-color, border-color, outline-color, fill, stroke, box-shadow, text-decoration-color, caret-color, column-rule-color 125ms ease-in-out"),
    ("ui/src/styles/tailwind-utilities.css", "color, background-color, border-color, outline-color, fill, stroke, box-shadow, text-decoration-color, caret-color, column-rule-color 125ms ease-in-out, transform 0.25s cubic-bezier(0.15, 1.4, 0.64, 0.96), opacity 0.25s cubic-bezier(0.15, 1.4, 0.64, 0.96), bottom 0.25s ease-in-out"),
    ("ui/src/styles/tailwind-utilities.css", "opacity 0.125s var(--ease-out-expo), scale 0.125s var(--ease-out-expo)"),
];

/// The names of every `@keyframes` the reference declares, in order.
///
/// Bodies are not copied: a keyframe is a sequence of property states, and
/// which of them a native port needs depends on the widget, so the shell
/// reads the reference for the one it is porting and cites this list.
pub const KEYFRAMES: &[(&str, &str)] = &[
    ("admonition-progress-waiting", "ui/src/components/base/Admonition.vue"),
    ("audit-log-bpulse", "ui/src/components/servers/access/AuditLogTable.vue"),
    ("backup-item-highlight-pulse", "ui/src/components/servers/backups/BackupItem.vue"),
    ("bpulse", "ui/src/components/base/BaseTerminal.vue"),
    ("breadcrumb-scroll", "app-frontend/src/components/ui/Breadcrumbs.vue"),
    ("breadcrumb-scroll", "ui/src/layouts/shared/files-tab/components/FileNavbar.vue"),
    ("dots", "ui/src/components/base/LoadingIndicator.vue"),
    ("fade-highlight", "app-frontend/src/components/ui/world/WorldItem.vue"),
    ("fade-opacity", "app-frontend/src/components/ui/world/WorldItem.vue"),
    ("floating-action-bar-attention", "ui/src/components/base/FloatingActionBar.vue"),
    ("indeterminate", "ui/src/layouts/shared/content-tab/components/ContentSelectionBar.vue"),
    ("indeterminate", "ui/src/layouts/wrapped/hosting/manage/backups.vue"),
    ("notification-bottom-progress-waiting", "ui/src/components/notifications/NotificationToast.vue"),
    ("pop", "app-frontend/src/App.vue"),
    ("pop", "ui/src/components/base/LoadingIndicator.vue"),
    ("progress-bar-waiting", "ui/src/components/base/ProgressBar.vue"),
    ("pulse", "ui/src/components/modal/ModalLoadingIndicator.vue"),
    ("rotate", "ui/src/components/brand/AnimatedLogo.vue"),
    ("server-action-buttons-anim", "ui/src/layouts/wrapped/hosting/manage/root.vue"),
    ("serverReveal", "ui/src/layouts/wrapped/hosting/manage/root.vue"),
    ("shimmer", "ui/src/components/base/LoadingIndicator.vue"),
    ("skeleton-pulse", "ui/src/components/skin/SkinButton.vue"),
    ("soft-pulse", "ui/src/components/base/I18nDebugPanel.vue"),
    ("spin", "ui/src/components/brand/TextLogo.vue"),
];

/// The theme the app opens in, and the one every measurement in
/// `REFERENCE.md` was taken in.
pub const DEFAULT_THEME: Theme = Theme::Dark;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_table_is_sorted_so_its_lookup_is_valid() {
        // `binary_search_by_key` is only a search if the table is sorted by
        // the same key, which is the one assumption the accessors make.
        for pair in INK_TABLE.windows(2) {
            assert!((pair[0].0 as u8) < (pair[1].0 as u8), "INK_TABLE is out of order");
        }
        for pair in SPAN_TABLE.windows(2) {
            assert!((pair[0].0 as u8) < (pair[1].0 as u8), "SPAN_TABLE is out of order");
        }
        for pair in FACTOR_TABLE.windows(2) {
            assert!((pair[0].0 as u8) < (pair[1].0 as u8), "FACTOR_TABLE is out of order");
        }
        for pair in CURVE_TABLE.windows(2) {
            assert!((pair[0].0 as u8) < (pair[1].0 as u8), "CURVE_TABLE is out of order");
        }
        for pair in RAW_TABLE.windows(2) {
            assert!((pair[0].0 as u8) < (pair[1].0 as u8), "RAW_TABLE is out of order");
        }
    }

    #[test]
    fn the_tables_cover_every_variant() {
        assert_eq!(INK_TABLE.len(), ALL_INK.len());
        assert_eq!(SPAN_TABLE.len(), ALL_SPAN.len());
        assert_eq!(FACTOR_TABLE.len(), ALL_FACTOR.len());
        assert_eq!(CURVE_TABLE.len(), ALL_CURVE.len());
        assert_eq!(RAW_TABLE.len(), ALL_RAW.len());
    }

    #[test]
    fn every_token_resolves_in_every_theme() {
        for theme in Theme::ALL {
            for token in ALL_INK {
                let [_, _, _, alpha] = ink_rgba(*theme, *token);
                // A colour with no value would resolve to transparent black,
                // which is only ever legitimate as an explicit `transparent`.
                let declared_transparent = ["Transparent", "AccentContrast"];
                let name = format!("{:?}", token);
                assert!(
                    alpha != 0 || declared_transparent.contains(&name.as_str()),
                    "{name} has no value in {theme:?}"
                );
            }
            for token in ALL_SPAN {
                assert!(span(*token) > 0.0, "{token:?} has no value");
            }
        }
    }

    #[test]
    fn the_surfaces_are_the_ones_the_reference_paints() {
        // Recorded in REFERENCE.md off the reference's own window: the page is
        // `#16181c` in dark, the chrome above it `#27292e`, and OLED takes the
        // page to true black.
        assert_eq!(ink_rgba(Theme::Dark, Ink::Surface1), [0x16, 0x18, 0x1c, 0xff]);
        assert_eq!(ink_rgba(Theme::Dark, Ink::Surface3), [0x27, 0x29, 0x2e, 0xff]);
        assert_eq!(ink_rgba(Theme::Oled, Ink::Surface1), [0x00, 0x00, 0x00, 0xff]);
        assert_eq!(ink_rgba(Theme::Light, Ink::Surface1), [0xeb, 0xeb, 0xeb, 0xff]);
        assert_eq!(ink_rgba(Theme::Retro, Ink::Surface1), [0x19, 0x19, 0x17, 0xff]);
    }

    #[test]
    fn the_accent_is_followed_through_its_indirection_per_theme() {
        // `--color-brand` is `var(--color-green)`, which is `var(--color-green-600)`
        // in light and `var(--color-green-500)` in dark, and is replaced outright in
        // retro. A generator that read the literal line would answer `var(...)` to
        // all four; this is the assertion that it followed the chain.
        assert_eq!(ink_rgba(Theme::Light, Ink::Brand), [0x00, 0xaf, 0x5c, 0xff]);
        assert_eq!(ink_rgba(Theme::Dark, Ink::Brand), [0x1b, 0xd9, 0x6a, 0xff]);
        assert_eq!(ink_rgba(Theme::Oled, Ink::Brand), [0x1b, 0xd9, 0x6a, 0xff]);
        assert_eq!(ink_rgba(Theme::Retro, Ink::Brand), [0x4d, 0x92, 0x27, 0xff]);
    }

    #[test]
    fn the_hover_factor_moves_the_way_the_reference_says() {
        // Two values, not one: light *darkens* a control under the pointer.
        assert_eq!(factor(Theme::Light, Factor::HoverBrightness), 0.9);
        assert_eq!(factor(Theme::Dark, Factor::HoverBrightness), 1.25);
        assert_eq!(factor(Theme::Retro, Factor::HoverBrightness), 1.25);
    }

    #[test]
    fn the_radii_are_rem_converted_at_the_browsers_own_root() {
        assert_eq!(span(Span::RadiusXs), 4.0);
        assert_eq!(span(Span::RadiusSm), 8.0);
        assert_eq!(span(Span::RadiusMd), 12.0);
        assert_eq!(span(Span::RadiusLg), 16.0);
        assert_eq!(span(Span::RadiusXl), 20.0);
    }

    #[test]
    fn the_reference_easing_is_the_one_it_declares() {
        assert_eq!(curve(Curve::EaseOutExpo), [0.16, 1.0, 0.3, 1.0]);
    }

    #[test]
    fn the_motion_table_is_not_empty_and_names_its_sources() {
        assert!(!MOTION.is_empty());
        for motion in MOTION {
            assert!(motion.millis > 0, "{} has no duration", motion.property);
            // The reference's longest transition is 2s. Every row past this
            // bound written so far was the generator's own unit error, not a
            // slow animation: `--check` compares bytes, so only a bound in the
            // tool catches a wrong number both files agree on.
            assert!(
                motion.millis <= 2000,
                "{} declares {}ms, longer than any transition in the reference",
                motion.property,
                motion.millis
            );
            assert!(motion.source.ends_with(".css") || motion.source.ends_with(".scss")
                || motion.source.ends_with(".vue"));
        }
        assert!(!KEYFRAMES.is_empty());
    }

    #[test]
    fn the_scale_the_markup_is_written_in_is_named() {
        // `p-4` is 16px and `text-sm` is 14px on a 20px line; the shell's
        // layout numbers are these, not chosen.
        assert!(TAILWIND.spacing.contains(&16.0));
        assert!(TAILWIND.font_size.contains(&(14.0, 20.0)));
        assert!(TAILWIND.font_weight.iter().any(|(_, w)| *w == 800));
    }
}
